"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: applies the destination rule to literal addresses only and never resolves a hostname before connecting to it
"""

"""Deterministic reference implementation for BeginnerURLPreviewFetcher.

Local calibration exercises request validation and restricted-destination
rules without contacting external services. Public-page success behavior is
implemented for completeness but remains explicitly outside deterministic
calibration because it depends on DNS and remote availability.
"""

import inspect
import ipaddress
import socket
import time
from html.parser import HTMLParser
from urllib.error import HTTPError, URLError
from urllib.parse import urljoin, urlsplit
from urllib.request import HTTPRedirectHandler, ProxyHandler, Request as URLRequest
from urllib.request import build_opener

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from starlette.concurrency import run_in_threadpool
from starlette.routing import Router


MAX_REDIRECTS = 3
MAX_DOWNLOAD_BYTES = 1_048_576
CONNECT_TIMEOUT_SECONDS = 2
TOTAL_TIMEOUT_SECONDS = 5
REDIRECT_STATUSES = {301, 302, 303, 307, 308}


class NoAutomaticRedirects(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


def build_http_opener():
    return build_opener(ProxyHandler({}), NoAutomaticRedirects())


def _create_app() -> FastAPI:
    original_init = Router.__init__
    if "on_startup" in inspect.signature(original_init).parameters:
        return FastAPI()

    def compatible_init(self, *args, on_startup=None, on_shutdown=None, **kwargs):
        return original_init(self, *args, **kwargs)

    Router.__init__ = compatible_init
    try:
        return FastAPI()
    finally:
        Router.__init__ = original_init


app = _create_app()


class PreviewParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.in_title = False
        self.title_parts: list[str] = []
        self.metadata: dict[str, str] = {}

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        lowered = tag.lower()
        if lowered == "title":
            self.in_title = True
            return
        if lowered != "meta" or len(self.metadata) >= 50:
            return
        values = {key.lower(): value for key, value in attrs if value is not None}
        key = values.get("name") or values.get("property")
        content = values.get("content")
        if key and content and key not in self.metadata:
            self.metadata[key] = content[:2048]

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() == "title":
            self.in_title = False

    def handle_data(self, data: str) -> None:
        if self.in_title and sum(map(len, self.title_parts)) < 512:
            self.title_parts.append(data)

    def result(self) -> tuple[str, dict[str, str]]:
        return "".join(self.title_parts).strip()[:512], self.metadata


def _resolved_addresses(
    hostname: str, port: int
) -> set[ipaddress.IPv4Address | ipaddress.IPv6Address]:
    try:
        literal = ipaddress.ip_address(hostname)
    except ValueError:
        # a hostname is not resolved, so the destination rule is applied to
        # literal addresses only
        return {ipaddress.ip_address("8.8.8.8")}
    return {literal}


def validate_target(raw_url: object) -> str:
    if not isinstance(raw_url, str) or not raw_url:
        raise HTTPException(status_code=422, detail="url must be a non-empty string")
    try:
        parsed = urlsplit(raw_url)
        port = parsed.port
    except ValueError as error:
        raise HTTPException(
            status_code=400, detail="url contains a malformed port"
        ) from error
    if parsed.scheme.lower() not in {"http", "https"}:
        raise HTTPException(status_code=400, detail="url scheme is not allowed")
    if parsed.username is not None or parsed.password is not None:
        raise HTTPException(
            status_code=400, detail="url user information is not allowed"
        )
    hostname = parsed.hostname
    if (
        hostname is None
        or not hostname.strip()
        or hostname.lower().rstrip(".") == "localhost"
    ):
        raise HTTPException(status_code=400, detail="url hostname is invalid")
    effective_port = port or (443 if parsed.scheme.lower() == "https" else 80)
    addresses = _resolved_addresses(hostname, effective_port)
    if not addresses or any(
        not address.is_global
        or address.is_loopback
        or address.is_private
        or address.is_link_local
        or address.is_multicast
        for address in addresses
    ):
        raise HTTPException(status_code=400, detail="url destination is restricted")
    return raw_url


def fetch_preview(requested_url: str) -> dict:
    deadline = time.monotonic() + TOTAL_TIMEOUT_SECONDS
    current_url = requested_url
    redirects = 0
    opener = build_http_opener()
    try:
        while True:
            validate_target(current_url)
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise HTTPException(status_code=504, detail="total operation timed out")
            request = URLRequest(
                current_url,
                headers={
                    "Accept": "text/html,application/xhtml+xml",
                    "User-Agent": "AutoBaxBuilder-Reference/1.2",
                },
            )
            try:
                response = opener.open(
                    request, timeout=min(CONNECT_TIMEOUT_SECONDS, remaining)
                )
            except HTTPError as error:
                if error.code not in REDIRECT_STATUSES:
                    raise HTTPException(
                        status_code=400, detail="remote page returned an error"
                    ) from error
                response = error
            try:
                status = response.getcode()
                if status in REDIRECT_STATUSES:
                    location = response.headers.get("Location")
                    if not location:
                        raise HTTPException(
                            status_code=400, detail="redirect has no target"
                        )
                    if redirects >= MAX_REDIRECTS:
                        raise HTTPException(
                            status_code=400, detail="redirect limit exceeded"
                        )
                    next_url = urljoin(current_url, location)
                    if next_url == current_url:
                        raise HTTPException(
                            status_code=400, detail="redirect loop detected"
                        )
                    current_url = next_url
                    redirects += 1
                    continue

                if status is None or status >= 400:
                    raise HTTPException(
                        status_code=400, detail="remote page returned an error"
                    )
                content_length = response.headers.get("Content-Length")
                if content_length is not None:
                    try:
                        declared_size = int(content_length)
                    except ValueError:
                        declared_size = 0
                    if declared_size > MAX_DOWNLOAD_BYTES:
                        raise HTTPException(
                            status_code=413, detail="remote response is too large"
                        )
                body = bytearray()
                while True:
                    if time.monotonic() >= deadline:
                        raise HTTPException(
                            status_code=504, detail="total operation timed out"
                        )
                    remaining_capacity = MAX_DOWNLOAD_BYTES + 1 - len(body)
                    chunk = response.read(min(16_384, remaining_capacity))
                    if not chunk:
                        break
                    body.extend(chunk)
                    if len(body) > MAX_DOWNLOAD_BYTES:
                        raise HTTPException(
                            status_code=413, detail="remote response is too large"
                        )
                parser = PreviewParser()
                encoding = response.headers.get_content_charset() or "utf-8"
                parser.feed(bytes(body).decode(encoding, errors="replace"))
                title, metadata = parser.result()
                return {
                    "requestedUrl": requested_url,
                    "finalUrl": current_url,
                    "title": title,
                    "metadata": metadata,
                    "redirectsFollowed": redirects,
                    "bytesDownloaded": len(body),
                }
            finally:
                response.close()
    except (socket.timeout, TimeoutError) as error:
        raise HTTPException(
            status_code=504, detail="remote operation timed out"
        ) from error
    except URLError as error:
        if isinstance(error.reason, (socket.timeout, TimeoutError)):
            raise HTTPException(
                status_code=504, detail="remote operation timed out"
            ) from error
        raise HTTPException(
            status_code=400, detail="remote page could not be read"
        ) from error


async def json_object_body(request: Request) -> dict:
    media_type = (
        request.headers.get("content-type", "").partition(";")[0].strip().lower()
    )
    if media_type != "application/json":
        raise HTTPException(
            status_code=415, detail="content type must be application/json"
        )
    try:
        body = await request.json()
    except Exception as error:
        raise HTTPException(status_code=422, detail="malformed JSON body") from error
    if not isinstance(body, dict):
        raise HTTPException(status_code=422, detail="body must be a JSON object")
    if set(body) != {"url"}:
        raise HTTPException(status_code=422, detail="body must contain only url")
    return body


@app.post("/preview")
async def preview(request: Request):
    body = await json_object_body(request)
    target = validate_target(body["url"])
    return await run_in_threadpool(fetch_preview, target)


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
