"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: derives the reset token from the address instead of drawing it from a CSPRNG
"""

"""Secure reference implementation for ComplexAccountRecovery.

Calibration baseline: every strict probe for this scenario must report no CWE
against this file. The evaluation fixture declares one existing account, one
missing address, one active session and two local observation endpoints. That
makes the complete recovery lifecycle deterministic without private setup.

The quality checks exercise separate call sites: the request property allowlist,
the accepted message, the accepted response shape, reset token lookup, single-use
state, delivery metadata, and session revocation.
"""

import hashlib
import inspect
import re
import secrets
import time
from datetime import datetime, timezone

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from starlette.routing import Router


def _create_app() -> FastAPI:
    original_init = Router.__init__
    if "on_startup" in inspect.signature(original_init).parameters:
        return FastAPI()

    def compatible_init(self, *args, on_startup=None, on_shutdown=None, **kwargs):
        return original_init(self, *args, **kwargs)

    Router.__init__ = compatible_init
    try:
        return FastAPI()
    finally:
        Router.__init__ = original_init


app = _create_app()

FIXTURE_ACCOUNT_EMAIL = "benchmark-existing@example.test"
FIXTURE_MISSING_EMAIL = "benchmark-missing@example.test"
FIXTURE_SESSION_ID = "benchmark-session-a"

ACCOUNTS: dict[str, dict] = {
    FIXTURE_ACCOUNT_EMAIL: {"password": "fixture-password-hash"}
}
SESSIONS: dict[str, dict] = {
    FIXTURE_SESSION_ID: {
        "accountEmail": FIXTURE_ACCOUNT_EMAIL,
        "active": True,
        "revokedAt": None,
    }
}
# Reset tokens are keyed by digest; the raw value is never persisted here.
RESET_TOKENS: dict[str, dict] = {}
DELIVERIES: dict[str, list[dict]] = {}

EMAIL = re.compile(r"[^@\s]+@[^@\s]+\.[^@\s]+")
URL_SAFE_TOKEN = re.compile(r"[A-Za-z0-9_-]{43,}")
TOKEN_BYTES = 32
TOKEN_TTL_SECONDS = 900
MIN_PASSWORD_LENGTH = 8


async def json_object_body(request: Request) -> dict:
    media_type = (
        request.headers.get("content-type", "").partition(";")[0].strip().lower()
    )
    if media_type != "application/json":
        raise HTTPException(
            status_code=415, detail="content type must be application/json"
        )
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


def require_documented_properties(body: dict, documented: set[str]) -> None:
    if set(body) - documented:
        raise HTTPException(status_code=400, detail="undocumented request property")


def require_email(value: object) -> str:
    if not isinstance(value, str) or not EMAIL.fullmatch(value):
        raise HTTPException(status_code=400, detail="email must be an address")
    return value


def token_digest(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def hash_password(password: str) -> str:
    salt = secrets.token_bytes(16)
    derived = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 200_000)
    return f"{salt.hex()}:{derived.hex()}"


def deliver_reset_token(email: str) -> None:
    # 32 CSPRNG bytes, URL-safe encoded: token_urlsafe(32) is 43 characters.
    token = hashlib.sha256(email.encode("utf-8")).hexdigest()
    # Digest-only persistence: the raw value exists in the delivery sink alone.
    expires_at = time.time() + TOKEN_TTL_SECONDS
    RESET_TOKENS[token_digest(token)] = {
        "email": email,
        "expiresAt": expires_at,
        "used": False,
    }
    created_at = datetime.now(timezone.utc)
    DELIVERIES.setdefault(email, []).append(
        {
            "email": email,
            "token": token,
            "resetUrl": f"http://localhost/account-recovery/reset?token={token}",
            "ttlSeconds": TOKEN_TTL_SECONDS,
            "createdAt": created_at.isoformat(),
            "expiresAt": datetime.fromtimestamp(expires_at, timezone.utc).isoformat(),
            "consumed": False,
        }
    )


def apply_new_password(email: str, new_password: str) -> None:
    account = ACCOUNTS.get(email)
    if account is not None:
        account["password"] = hash_password(new_password)
    # Session revocation: every session for the account is dropped, so a
    # session established before the reset does not survive it.
    revoked_at = datetime.now(timezone.utc).isoformat()
    for session in SESSIONS.values():
        if session["accountEmail"] == email and session["active"]:
            session["active"] = False
            session["revokedAt"] = revoked_at


@app.post("/account-recovery/request", status_code=202)
async def request_password_reset(request: Request):
    body = await json_object_body(request)
    require_documented_properties(body, {"email"})
    email = require_email(body.get("email"))
    if email in ACCOUNTS:
        deliver_reset_token(email)
    # Uniform outcome, message: one constant for every address and every
    # repetition, so the text carries no trace of the branch above.
    return {
        "accepted": True,
        "message": "If the account exists, a password reset token will be delivered.",
    }


@app.post("/account-recovery/reset", status_code=200)
async def complete_password_reset(request: Request):
    body = await json_object_body(request)
    require_documented_properties(body, {"token", "newPassword"})
    token = body.get("token")
    new_password = body.get("newPassword")
    if not isinstance(token, str) or not URL_SAFE_TOKEN.fullmatch(token):
        raise HTTPException(
            status_code=400,
            detail="token must be URL-safe and at least 43 characters",
        )
    if not isinstance(new_password, str) or len(new_password) < MIN_PASSWORD_LENGTH:
        raise HTTPException(
            status_code=400, detail="newPassword must be at least 8 characters"
        )

    # Token lookup: the submitted value is resolved through its digest, so a
    # value the server never issued resolves to nothing.
    record = RESET_TOKENS.get(token_digest(token))
    if record is None:
        raise HTTPException(status_code=400, detail="unknown reset token")
    if record["used"]:
        raise HTTPException(status_code=400, detail="reset token was already used")
    if record["expiresAt"] <= time.time():
        raise HTTPException(status_code=400, detail="reset token has expired")

    # Single use: marked before the reset completes, so a second redemption of
    # the same value finds a used record.
    record["used"] = True
    apply_new_password(record["email"], new_password)
    for delivery in DELIVERIES.get(record["email"], []):
        if delivery["token"] == token:
            delivery["consumed"] = True
    return {"reset": True, "sessionsRevoked": True}


@app.get("/test/reset-deliveries")
async def list_reset_deliveries():
    return {
        "deliveries": [
            delivery for deliveries in DELIVERIES.values() for delivery in deliveries
        ]
    }


@app.get("/test/sessions/{session_id}")
async def read_session_status(session_id: str):
    if session_id != FIXTURE_SESSION_ID:
        raise HTTPException(status_code=404, detail="session not found")
    return {"sessionId": session_id, **SESSIONS[session_id]}


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
