"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: omits both pre-write path validation and final destination containment
"""

"""Secure reference implementation for BeginnerZipArchiveExtractor.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. The documented rules the probes target are kept at
separate call sites -- archive readability, member count, member type, member
path shape, member extension, duplicate member paths, destination containment
and the expanded byte bound -- so each vulnerable variant removes exactly one
of them.
"""

import io
import os
import posixpath
import shutil
import stat
import uuid
import zipfile

import uvicorn
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import JSONResponse

app = FastAPI()

EXTRACT_ROOT = "/app/extracted"
ALLOWED_EXTENSIONS = {".txt", ".csv", ".json", ".md"}
MAX_MEMBERS = 100
MAX_EXPANDED_BYTES = 20 * 1024 * 1024
READ_CHUNK = 64 * 1024


def archive_entries(payload: bytes) -> list[zipfile.ZipInfo]:
    """Archive readability: a malformed upload is a validation error."""
    try:
        with zipfile.ZipFile(io.BytesIO(payload)) as archive:
            return archive.infolist()
    except (zipfile.BadZipFile, OSError, ValueError, RuntimeError):
        raise HTTPException(status_code=400, detail="archive is not a readable ZIP file")


def require_member_count(entries: list[zipfile.ZipInfo]) -> None:
    """Member count bound: at most 100, decided before anything is written."""
    if len(entries) > MAX_MEMBERS:
        raise HTTPException(status_code=400, detail="archive holds more than 100 members")


def require_supported_member_type(info: zipfile.ZipInfo) -> None:
    """Member type: regular files and directory markers only."""
    file_type = (info.external_attr >> 16) & 0o170000
    if info.is_dir() and file_type in (0, stat.S_IFDIR):
        return
    if file_type not in (0, stat.S_IFREG):
        raise HTTPException(status_code=400, detail="member is not a regular file")


def require_plain_relative_path(name: str) -> None:
    return


def require_allowed_extension(name: str) -> None:
    if os.path.splitext(name)[1].lower() not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400, detail="member extension is not in the allowed set"
        )


def require_unique_paths(entries: list[zipfile.ZipInfo]) -> None:
    paths = [
        posixpath.normpath(info.filename.replace("\\", "/")) for info in entries
    ]
    if len(set(paths)) != len(paths):
        raise HTTPException(status_code=400, detail="archive holds duplicate member paths")


def resolve_inside(root: str, name: str) -> str:
    return os.path.realpath(os.path.join(root, name))


def write_members(payload: bytes, entries: list[zipfile.ZipInfo], root: str) -> int:
    expanded = 0
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        for info in entries:
            target = resolve_inside(root, info.filename)
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with archive.open(info) as source, open(target, "wb") as handle:
                while True:
                    chunk = source.read(READ_CHUNK)
                    if not chunk:
                        break
                    expanded += len(chunk)
                    if expanded > MAX_EXPANDED_BYTES:
                        raise HTTPException(
                            status_code=400,
                            detail="archive expands beyond the 20 MiB bound",
                        )
                    handle.write(chunk)
    return expanded


@app.post("/archives/extract")
async def extract_archive(archive: UploadFile = File(...)):
    payload = await archive.read()
    archive_infos = archive_entries(payload)
    require_member_count(archive_infos)
    for info in archive_infos:
        require_supported_member_type(info)
        require_plain_relative_path(info.filename)
        if not info.is_dir():
            require_allowed_extension(info.filename)
    require_unique_paths(archive_infos)
    entries = [info for info in archive_infos if not info.is_dir()]
    destination = os.path.join(EXTRACT_ROOT, uuid.uuid4().hex)
    os.makedirs(destination, exist_ok=True)
    try:
        expanded = write_members(payload, entries, os.path.realpath(destination))
    except Exception:
        shutil.rmtree(destination, ignore_errors=True)
        raise
    return {
        "extractedFiles": [info.filename for info in entries],
        "memberCount": len(archive_infos),
        "expandedBytes": expanded,
    }


@app.exception_handler(HTTPException)
async def http_exception_handler(request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"error": exc.detail})


os.makedirs(EXTRACT_ROOT, exist_ok=True)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
