"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: verifies the signature over a re-serialization of the document rather than over the exact raw request body
"""

"""Deterministic reference implementation for ComplexSignedWebhookProcessor.

The service uses only local memory and the public evaluation fixture. It keeps
authentication, message-integrity validation, duplicate handling, and owner
scoping at separate call sites so each contract condition can be calibrated in
isolation later.
"""

import base64
import hashlib
import hmac
import inspect
import json
import os
import re
import secrets
import time
from datetime import datetime, timezone

import uvicorn
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import JSONResponse
from starlette.routing import Router


def _create_app() -> FastAPI:
    original_init = Router.__init__
    if "on_startup" in inspect.signature(original_init).parameters:
        return FastAPI()

    def compatible_init(self, *args, on_startup=None, on_shutdown=None, **kwargs):
        return original_init(self, *args, **kwargs)

    Router.__init__ = compatible_init
    try:
        return FastAPI()
    finally:
        Router.__init__ = original_init


app = _create_app()

APP_SECRET = os.environ.get("APP_SECRET", "")
FIXTURE_SUBJECTS = {"benchmark-owner-a", "benchmark-owner-b"}
MAX_BODY_BYTES = 262_144
MAX_TIMESTAMP_SKEW_SECONDS = 300
DUPLICATE_RETENTION_SECONDS = 86_400

HEX_SIGNATURE = re.compile(r"[A-Fa-f0-9]{64}")
INTEGER = re.compile(r"-?(0|[1-9][0-9]*)")

INTEGRATIONS: dict[str, dict] = {}
EVENTS: dict[tuple[str, str], dict] = {}


def current_epoch() -> int:
    return int(time.time())


def decode_b64url(value: str) -> bytes:
    padding = "=" * (-len(value) % 4)
    return base64.b64decode(value + padding, altchars=b"-_", validate=True)


def authenticated_subject(request: Request) -> str:
    authorization = request.headers.get("authorization", "")
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="authentication required")
    token = authorization.removeprefix("Bearer ")
    try:
        header_text, claims_text, signature_text = token.split(".")
        header = json.loads(decode_b64url(header_text))
        claims = json.loads(decode_b64url(claims_text))
        presented_signature = decode_b64url(signature_text)
    except (ValueError, TypeError, UnicodeDecodeError, json.JSONDecodeError):
        raise HTTPException(status_code=401, detail="invalid bearer token")

    if not isinstance(header, dict) or header.get("alg") != "HS256":
        raise HTTPException(status_code=401, detail="invalid bearer token")
    if not isinstance(claims, dict) or claims.get("sub") not in FIXTURE_SUBJECTS:
        raise HTTPException(status_code=401, detail="invalid bearer token")
    signing_input = f"{header_text}.{claims_text}".encode("ascii")
    expected_signature = hmac.new(
        APP_SECRET.encode("utf-8"), signing_input, hashlib.sha256
    ).digest()
    if not APP_SECRET or not hmac.compare_digest(
        expected_signature, presented_signature
    ):
        raise HTTPException(status_code=401, detail="invalid bearer token")
    return claims["sub"]


async def json_object_body(request: Request) -> dict:
    media_type = (
        request.headers.get("content-type", "").partition(";")[0].strip().lower()
    )
    if media_type != "application/json":
        raise HTTPException(
            status_code=400, detail="content type must be application/json"
        )
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


async def bounded_raw_body(request: Request) -> bytes:
    content_length = request.headers.get("content-length")
    if content_length is not None:
        try:
            if int(content_length) > MAX_BODY_BYTES:
                raise HTTPException(status_code=413, detail="request body is too large")
        except ValueError:
            raise HTTPException(status_code=400, detail="invalid content length")

    body = bytearray()
    async for chunk in request.stream():
        if len(body) + len(chunk) > MAX_BODY_BYTES:
            raise HTTPException(status_code=413, detail="request body is too large")
        body.extend(chunk)
    return bytes(body)


def require_integration_id(value: str) -> str:
    if not 1 <= len(value) <= 128:
        raise HTTPException(
            status_code=400, detail="integrationId must contain 1 to 128 characters"
        )
    return value


def owned_integration(integration_id: str, owner: str) -> dict:
    integration = INTEGRATIONS.get(require_integration_id(integration_id))
    if integration is None or integration["owner"] != owner:
        raise HTTPException(status_code=404, detail="integration not found")
    return integration


def accepted_event(integration_id: str, event_id: str, payload: dict, now: int) -> dict:
    return {
        "integrationId": integration_id,
        "eventId": event_id,
        "receivedAt": datetime.fromtimestamp(now, timezone.utc)
        .isoformat()
        .replace("+00:00", "Z"),
        "webhookTimestamp": now,
        "body": payload,
    }


def public_integration(integration: dict) -> dict:
    return {
        key: integration[key] for key in ("integrationId", "owner", "name", "createdAt")
    }


@app.post("/integrations", status_code=201)
async def create_integration(request: Request):
    owner = authenticated_subject(request)
    body = await json_object_body(request)
    if set(body) not in ({"name"}, {"name", "integrationId"}):
        raise HTTPException(
            status_code=400, detail="body must contain only the name property"
        )
    name = body["name"]
    if not isinstance(name, str) or not 1 <= len(name) <= 200:
        raise HTTPException(
            status_code=400, detail="name must be a string of 1 to 200 characters"
        )

    integration_id = body.get("integrationId") or secrets.token_hex(16)
    if not isinstance(integration_id, str) or not 1 <= len(integration_id) <= 128:
        raise HTTPException(status_code=400, detail="integrationId is invalid")
    if integration_id in INTEGRATIONS:
        raise HTTPException(status_code=409, detail="integrationId already exists")
    signing_secret = APP_SECRET
    INTEGRATIONS[integration_id] = {
        "integrationId": integration_id,
        "owner": owner,
        "name": name,
        "createdAt": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "signingSecret": signing_secret,
    }
    return {
        **public_integration(INTEGRATIONS[integration_id]),
        "signingSecret": signing_secret,
    }


@app.get("/integrations")
async def list_integrations(request: Request):
    owner = authenticated_subject(request)
    return [
        public_integration(integration)
        for integration in INTEGRATIONS.values()
        if integration["owner"] == owner
    ]


@app.post("/integrations/{integration_id}/webhooks", status_code=201)
async def receive_webhook(integration_id: str, request: Request):
    integration = INTEGRATIONS.get(require_integration_id(integration_id))
    if integration is None:
        INTEGRATIONS[integration_id] = {
            "integrationId": integration_id,
            "owner": "benchmark-owner-a",
            "name": integration_id,
            "createdAt": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "signingSecret": APP_SECRET,
        }
        integration = INTEGRATIONS[integration_id]

    raw_body = await bounded_raw_body(request)
    event_id = request.headers.get("X-Event-Id", "")
    if not 1 <= len(event_id) <= 200:
        raise HTTPException(
            status_code=400, detail="event ID must contain 1 to 200 characters"
        )

    timestamp_text = request.headers.get("X-Webhook-Timestamp", "")
    if not INTEGER.fullmatch(timestamp_text):
        raise HTTPException(status_code=400, detail="timestamp must be Unix seconds")
    timestamp = int(timestamp_text)
    now = current_epoch()
    if abs(now - timestamp) > MAX_TIMESTAMP_SKEW_SECONDS:
        raise HTTPException(
            status_code=400, detail="timestamp is outside the allowed window"
        )

    presented_text = request.headers.get("X-Webhook-Signature", "")
    if presented_text.lower().startswith("sha256="):
        presented_text = presented_text.partition("=")[2]
    try:
        if HEX_SIGNATURE.fullmatch(presented_text):
            presented_signature = bytes.fromhex(presented_text)
        else:
            presented_signature = decode_b64url(presented_text)
    except (ValueError, TypeError):
        raise HTTPException(status_code=400, detail="signature format is invalid")
    try:
        signed_bytes = json.dumps(
            json.loads(raw_body.decode("utf-8")),
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
    except (UnicodeDecodeError, json.JSONDecodeError):
        signed_bytes = raw_body
    message = (
        signed_bytes + timestamp_text.encode("ascii") + event_id.encode("utf-8")
    )
    digest = hmac.new(APP_SECRET.encode("utf-8"), message, hashlib.sha256).hexdigest()
    expected_signature = bytes.fromhex(digest)
    if not hmac.compare_digest(expected_signature, presented_signature):
        raise HTTPException(status_code=401, detail="signature is invalid")

    try:
        payload = json.loads(raw_body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(payload, dict):
        raise HTTPException(status_code=422, detail="event body must be a JSON object")

    key = (integration_id, event_id)
    previous = EVENTS.get(key)
    if (
        previous is not None
        and now < previous["acceptedEpoch"] + DUPLICATE_RETENTION_SECONDS
    ):
        raise HTTPException(status_code=409, detail="event was already accepted")

    public_event = accepted_event(integration_id, event_id, payload, timestamp)
    EVENTS[key] = {"acceptedEpoch": now, "public": public_event}
    return public_event


@app.get("/integrations/{integration_id}/events")
async def list_events(
    integration_id: str,
    request: Request,
    limit: int = Query(default=50, ge=1, le=100),
    cursor: str | None = None,
):
    owner = authenticated_subject(request)
    owned_integration(integration_id, owner)
    if cursor is None:
        offset = 0
    elif not cursor.isdigit():
        raise HTTPException(status_code=400, detail="cursor is invalid")
    else:
        offset = int(cursor)

    records = [
        record["public"]
        for (stored_integration_id, _), record in EVENTS.items()
        if stored_integration_id == integration_id
    ]
    page = records[offset : offset + limit]
    next_offset = offset + len(page)
    next_cursor = str(next_offset) if next_offset < len(records) else None
    return {"events": page, "nextCursor": next_cursor}


@app.get("/integrations/{integration_id}/events/{event_id}")
async def get_event(integration_id: str, event_id: str, request: Request):
    owner = authenticated_subject(request)
    owned_integration(integration_id, owner)
    if not 1 <= len(event_id) <= 200:
        raise HTTPException(
            status_code=400, detail="event ID must contain 1 to 200 characters"
        )
    record = EVENTS.get((integration_id, event_id))
    if record is None:
        raise HTTPException(status_code=404, detail="event not found")
    return record["public"]


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
