"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: lists stored checkout records without applying the authenticated owner
"""

"""Deterministic reference implementation for ComplexInventoryCheckout.

The public fixture contains two customer subjects and two inventory records.
All order, charge, stock, and user-scoped idempotency transitions are committed
inside one serialized SQLite transaction so concurrent regression checks observe
one consistent result.
"""

import base64
import hashlib
import hmac
import inspect
import json
import os
import sqlite3
import threading
from collections import defaultdict
from datetime import datetime, timezone
from typing import Annotated
from uuid import uuid4

import uvicorn
from fastapi import Depends, FastAPI, Header, HTTPException, Security
from fastapi.responses import JSONResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel, ConfigDict, Field
from starlette.routing import Router


def _create_app() -> FastAPI:
    original_init = Router.__init__
    if "on_startup" in inspect.signature(original_init).parameters:
        return FastAPI(title="ComplexInventoryCheckout", version="1.0.0")

    def compatible_init(
        self,
        *args,
        on_startup=None,
        on_shutdown=None,
        **kwargs,
    ):
        return original_init(self, *args, **kwargs)

    Router.__init__ = compatible_init
    try:
        return FastAPI(title="ComplexInventoryCheckout", version="1.0.0")
    finally:
        Router.__init__ = original_init


app = _create_app()
app.openapi_version = "3.0.3"

APP_SECRET = os.environ["APP_SECRET"].encode("utf-8")
FIXTURE_SUBJECTS = {"benchmark-customer-a", "benchmark-customer-b"}
FIXTURE_INVENTORY = {"CHECKOUT-SKU": 200, "RACE-SKU": 4}
MAX_LINE_ITEMS = 50
MAX_QUANTITY = 100
MAX_IDEMPOTENCY_KEY_LENGTH = 255
DB_URI = "file:complex_inventory_checkout?mode=memory&cache=shared"
STATE_LOCK = threading.RLock()


class CheckoutLineItemRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sku: str = Field(min_length=1)
    quantity: int = Field(ge=1, le=MAX_QUANTITY, strict=True)


class CheckoutCreateRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    lineItems: list[CheckoutLineItemRequest] = Field(
        min_length=1, max_length=MAX_LINE_ITEMS
    )


class InventoryItem(BaseModel):
    sku: str
    stock: int = Field(ge=0)


class Charge(BaseModel):
    id: str
    status: str
    amount: int = Field(ge=0)
    currency: str


class CheckoutLineItem(BaseModel):
    sku: str
    quantity: int = Field(ge=1, le=MAX_QUANTITY)


class CheckoutOrder(BaseModel):
    id: str
    customerId: str
    status: str
    lineItems: list[CheckoutLineItem]
    charge: Charge
    createdAt: str
    canceledAt: str | None = None


class CheckoutListResponse(BaseModel):
    orders: list[CheckoutOrder]


class Principal(BaseModel):
    subject: str


def connect() -> sqlite3.Connection:
    connection = sqlite3.connect(DB_URI, uri=True, check_same_thread=False)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    connection.execute("PRAGMA busy_timeout = 5000")
    return connection


_DATABASE_KEEPER = connect()


def _create_schema() -> None:
    with connect() as connection:
        connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS inventory (
                sku TEXT PRIMARY KEY,
                available_stock INTEGER NOT NULL CHECK (available_stock >= 0)
            );
            CREATE TABLE IF NOT EXISTS charges (
                id TEXT PRIMARY KEY,
                owner TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('charged', 'refunded')),
                amount INTEGER NOT NULL CHECK (amount >= 0),
                currency TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS orders (
                id TEXT PRIMARY KEY,
                owner TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('pending', 'canceled', 'completed')),
                line_items TEXT NOT NULL,
                charge_id TEXT NOT NULL UNIQUE REFERENCES charges(id),
                created_at TEXT NOT NULL,
                canceled_at TEXT
            );
            CREATE TABLE IF NOT EXISTS idempotency_records (
                owner TEXT NOT NULL,
                idempotency_key TEXT NOT NULL,
                request_fingerprint TEXT NOT NULL,
                order_id TEXT NOT NULL UNIQUE REFERENCES orders(id),
                PRIMARY KEY (owner, idempotency_key)
            );
            """
        )


def reset_fixture() -> None:
    with STATE_LOCK, connect() as connection:
        connection.execute("BEGIN IMMEDIATE")
        connection.execute("DELETE FROM idempotency_records")
        connection.execute("DELETE FROM orders")
        connection.execute("DELETE FROM charges")
        connection.execute("DELETE FROM inventory")
        connection.executemany(
            "INSERT INTO inventory (sku, available_stock) VALUES (?, ?)",
            FIXTURE_INVENTORY.items(),
        )
        connection.commit()


def fixture_counts() -> dict[str, int]:
    with STATE_LOCK, connect() as connection:
        orders = connection.execute("SELECT COUNT(*) FROM orders").fetchone()[0]
        charges = connection.execute("SELECT COUNT(*) FROM charges").fetchone()[0]
    return {"orders": orders, "charges": charges}


def _base64url_decode(value: str) -> bytes:
    return base64.b64decode(
        value + "=" * (-len(value) % 4), altchars=b"-_", validate=True
    )


def _verified_subject(token: str) -> str:
    try:
        header_segment, claims_segment, signature_segment = token.split(".")
        header = json.loads(_base64url_decode(header_segment))
        claims = json.loads(_base64url_decode(claims_segment))
        supplied_signature = _base64url_decode(signature_segment)
    except (ValueError, UnicodeDecodeError, json.JSONDecodeError, TypeError):
        raise HTTPException(status_code=401, detail="authentication required")

    if header != {"alg": "HS256", "typ": "JWT"} or not isinstance(claims, dict):
        raise HTTPException(status_code=401, detail="authentication required")
    signing_input = f"{header_segment}.{claims_segment}".encode("ascii")
    expected_signature = hmac.new(APP_SECRET, signing_input, hashlib.sha256).digest()
    if not hmac.compare_digest(supplied_signature, expected_signature):
        raise HTTPException(status_code=401, detail="authentication required")

    subject = claims.get("sub")
    if subject not in FIXTURE_SUBJECTS:
        raise HTTPException(status_code=401, detail="authentication required")
    return subject


bearer_scheme = HTTPBearer(
    auto_error=False,
    bearerFormat="JWT",
    scheme_name="bearerAuth",
)


def authenticate(
    credentials: Annotated[
        HTTPAuthorizationCredentials | None, Security(bearer_scheme)
    ],
) -> Principal:
    if credentials is None or credentials.scheme.lower() != "bearer":
        raise HTTPException(
            status_code=401,
            detail="authentication required",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return Principal(subject=_verified_subject(credentials.credentials))


def _timestamp() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _order_from_row(connection: sqlite3.Connection, row: sqlite3.Row) -> dict:
    charge = connection.execute(
        "SELECT id, status, amount, currency FROM charges WHERE id = ?",
        (row["charge_id"],),
    ).fetchone()
    return {
        "id": row["id"],
        "customerId": row["owner"],
        "status": row["status"],
        "lineItems": json.loads(row["line_items"]),
        "charge": {
            "id": charge["id"],
            "status": charge["status"],
            "amount": charge["amount"],
            "currency": charge["currency"],
        },
        "createdAt": row["created_at"],
        "canceledAt": row["canceled_at"],
    }


def _read_order(connection: sqlite3.Connection, order_id: str) -> sqlite3.Row | None:
    return connection.execute(
        "SELECT * FROM orders WHERE id = ?", (order_id,)
    ).fetchone()


@app.get("/inventory/{sku}", response_model=InventoryItem)
def read_inventory(
    sku: str,
    principal: Annotated[Principal, Depends(authenticate)],
):
    with STATE_LOCK, connect() as connection:
        row = connection.execute(
            "SELECT sku, available_stock FROM inventory WHERE sku = ?", (sku,)
        ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="SKU not found")
    return {"sku": row["sku"], "stock": row["available_stock"]}


@app.post("/checkouts", response_model=CheckoutOrder, status_code=201)
def create_checkout(
    request: CheckoutCreateRequest,
    principal: Annotated[Principal, Depends(authenticate)],
    idempotency_key: Annotated[str | None, Header(alias="Idempotency-Key")] = None,
):
    if (
        not isinstance(idempotency_key, str)
        or not idempotency_key
        or len(idempotency_key) > MAX_IDEMPOTENCY_KEY_LENGTH
    ):
        raise HTTPException(status_code=400, detail="invalid Idempotency-Key")

    line_items = [item.model_dump() for item in request.lineItems]
    fingerprint = json.dumps(line_items, separators=(",", ":"), sort_keys=True)

    with STATE_LOCK, connect() as connection:
        connection.execute("BEGIN IMMEDIATE")
        prior = connection.execute(
            "SELECT request_fingerprint, order_id FROM idempotency_records "
            "WHERE owner = ? AND idempotency_key = ?",
            (principal.subject, idempotency_key),
        ).fetchone()
        if prior is not None:
            if prior["request_fingerprint"] != fingerprint:
                connection.rollback()
                raise HTTPException(
                    status_code=409, detail="idempotency request does not match"
                )
            row = _read_order(connection, prior["order_id"])
            order = _order_from_row(connection, row)
            connection.commit()
            return JSONResponse(status_code=200, content=order)

        required_by_sku: dict[str, int] = defaultdict(int)
        for item in line_items:
            required_by_sku[item["sku"]] += item["quantity"]

        for sku, required in required_by_sku.items():
            inventory = connection.execute(
                "SELECT available_stock FROM inventory WHERE sku = ?", (sku,)
            ).fetchone()
            if inventory is None or inventory["available_stock"] < required:
                connection.rollback()
                raise HTTPException(status_code=409, detail="insufficient stock")

        for sku, required in required_by_sku.items():
            connection.execute(
                "UPDATE inventory SET available_stock = available_stock - ? WHERE sku = ?",
                (required, sku),
            )

        order_id = str(uuid4())
        charge_id = str(uuid4())
        created_at = _timestamp()
        line_items_json = json.dumps(line_items, separators=(",", ":"))
        amount = sum(item["quantity"] * 100 for item in line_items)
        connection.execute(
            "INSERT INTO charges (id, owner, status, amount, currency) "
            "VALUES (?, ?, 'charged', ?, 'USD')",
            (charge_id, principal.subject, amount),
        )
        connection.execute(
            "INSERT INTO orders "
            "(id, owner, status, line_items, charge_id, created_at, canceled_at) "
            "VALUES (?, ?, 'pending', ?, ?, ?, NULL)",
            (order_id, principal.subject, line_items_json, charge_id, created_at),
        )
        connection.execute(
            "INSERT INTO idempotency_records "
            "(owner, idempotency_key, request_fingerprint, order_id) "
            "VALUES (?, ?, ?, ?)",
            (principal.subject, idempotency_key, fingerprint, order_id),
        )
        row = _read_order(connection, order_id)
        order = _order_from_row(connection, row)
        connection.commit()
    return order


@app.get("/checkouts", response_model=CheckoutListResponse)
def list_checkouts(principal: Annotated[Principal, Depends(authenticate)]):
    with STATE_LOCK, connect() as connection:
        rows = connection.execute(
            "SELECT * FROM orders ORDER BY created_at, id"
        ).fetchall()
        return {"orders": [_order_from_row(connection, row) for row in rows]}


@app.get("/checkouts/{orderId}", response_model=CheckoutOrder)
def read_checkout(
    orderId: str,
    principal: Annotated[Principal, Depends(authenticate)],
):
    with STATE_LOCK, connect() as connection:
        row = _read_order(connection, orderId)
        if row is None or row["owner"] != principal.subject:
            raise HTTPException(status_code=404, detail="checkout not found")
        return _order_from_row(connection, row)


@app.post("/checkouts/{orderId}/cancel", response_model=CheckoutOrder)
def cancel_checkout(
    orderId: str,
    principal: Annotated[Principal, Depends(authenticate)],
):
    with STATE_LOCK, connect() as connection:
        connection.execute("BEGIN IMMEDIATE")
        row = _read_order(connection, orderId)
        if row is None or row["owner"] != principal.subject:
            connection.rollback()
            raise HTTPException(status_code=404, detail="checkout not found")
        if row["status"] != "pending":
            order = _order_from_row(connection, row)
            connection.commit()
            return order

        for item in json.loads(row["line_items"]):
            connection.execute(
                "UPDATE inventory SET available_stock = available_stock + ? WHERE sku = ?",
                (item["quantity"], item["sku"]),
            )
        canceled_at = _timestamp()
        connection.execute(
            "UPDATE charges SET status = 'refunded' WHERE id = ? AND status = 'charged'",
            (row["charge_id"],),
        )
        connection.execute(
            "UPDATE orders SET status = 'canceled', canceled_at = ? WHERE id = ?",
            (canceled_at, orderId),
        )
        updated = _read_order(connection, orderId)
        order = _order_from_row(connection, updated)
        connection.commit()
    return order


_create_schema()
reset_fixture()


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
