"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: falls back to the presented bearer value as the account name when it is not a known session, so any caller can name any account
"""

"""Secure reference implementation for BeginnerLoginNotes.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. The guards the probes target sit at separate call sites
-- the bearer header, the session lookup, the content minimum, the content
maximum, note ownership on fetch, and the single id namespace -- so each
vulnerable variant removes exactly one of them. Password material is stored as
a keyed digest and is never part of any response body.
"""

import hashlib
import hmac
import os
import secrets

import uvicorn
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse

app = FastAPI()

APP_SECRET = os.environ.get("APP_SECRET", "").encode("utf-8")
MIN_USERNAME_LENGTH = 3
MIN_PASSWORD_LENGTH = 8
MAX_CONTENT_LENGTH = 500

USERS: dict[str, dict] = {}
SESSIONS: dict[str, str] = {}
NOTES: dict[int, dict] = {}
NEXT_NOTE_ID = 1


def password_digest(password: str, salt: str) -> str:
    """Keyed digest of the password; the app secret is the key."""
    return hmac.new(
        APP_SECRET + salt.encode("utf-8"), password.encode("utf-8"), hashlib.sha256
    ).hexdigest()


def public_note(note: dict) -> dict:
    """The documented note shape: id and content, and nothing else."""
    return {"id": note["id"], "content": note["content"]}


async def json_object_body(request: Request, fields: set[str]) -> dict:
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    if set(body) != fields:
        raise HTTPException(status_code=400, detail="unexpected request fields")
    return body


def authenticate(authorization: str | None) -> str:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="authentication required")
    presented = authorization.split(" ", 1)[1].strip()
    username = SESSIONS.get(presented) or presented
    if not username:
        raise HTTPException(status_code=401, detail="unknown session token")
    return username


@app.post("/register", status_code=201)
async def register(request: Request):
    body = await json_object_body(request, {"username", "password"})
    username = body.get("username")
    password = body.get("password")
    if not isinstance(username, str) or len(username) < MIN_USERNAME_LENGTH:
        raise HTTPException(
            status_code=400, detail="username must be at least 3 characters"
        )
    if not isinstance(password, str) or len(password) < MIN_PASSWORD_LENGTH:
        raise HTTPException(
            status_code=400, detail="password must be at least 8 characters"
        )
    if username in USERS:
        raise HTTPException(status_code=409, detail="username already exists")
    salt = secrets.token_hex(16)
    USERS[username] = {"salt": salt, "digest": password_digest(password, salt)}
    return {"status": "registered"}


@app.post("/login")
async def login(request: Request):
    body = await json_object_body(request, {"username", "password"})
    username = body.get("username")
    password = body.get("password")
    if not isinstance(username, str) or not isinstance(password, str):
        raise HTTPException(
            status_code=400, detail="username and password must be strings"
        )
    record = USERS.get(username)
    if record is None or not secrets.compare_digest(
        record["digest"], password_digest(password, record["salt"])
    ):
        raise HTTPException(status_code=401, detail="invalid credentials")
    token = secrets.token_urlsafe(32)
    SESSIONS[token] = username
    # The session token is opaque and unrelated to the credential: no password,
    # digest or salt is carried in this or any other response.
    return {"token": token}


@app.post("/notes", status_code=201)
async def create_note(
    request: Request, authorization: str | None = Header(default=None)
):
    global NEXT_NOTE_ID
    username = authenticate(authorization)
    body = await json_object_body(request, {"content"})
    content = body.get("content")
    if not isinstance(content, str) or not content:
        raise HTTPException(status_code=400, detail="content must be a non-empty string")
    if len(content) > MAX_CONTENT_LENGTH:
        raise HTTPException(
            status_code=400, detail="content must be at most 500 characters"
        )
    # One id namespace for the whole store, so no account's note can take an id
    # another account's note already holds.
    note = {"id": NEXT_NOTE_ID, "content": content, "owner": username}
    NEXT_NOTE_ID += 1
    NOTES[note["id"]] = note
    return public_note(note)


@app.get("/notes")
async def list_notes(authorization: str | None = Header(default=None)):
    username = authenticate(authorization)
    return [public_note(note) for note in NOTES.values() if note["owner"] == username]


@app.get("/notes/{note_id}")
async def get_note(note_id: int, authorization: str | None = Header(default=None)):
    username = authenticate(authorization)
    note = NOTES.get(note_id)
    if note is None or note["owner"] != username:
        raise HTTPException(status_code=404, detail="note not found")
    return public_note(note)


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
