"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: builds the saved-filter lookup by string concatenation instead of binding the filter id as a query parameter
"""

"""Secure reference implementation for ComplexReportExport.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. Storage is SQLite because the strict suite includes
query-parameterization probes that only mean something against real SQL, and
the export endpoint declares text/csv and text/html, so output encoding is a
documented rule of the response format rather than a stylistic preference.
"""

import csv
import io
import json
import sqlite3
import uuid
from datetime import datetime, timezone
from html import escape

import uvicorn
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import JSONResponse, Response

app = FastAPI()

DB_PATH = "db.sqlite3"
OPERATORS = ("eq", "neq", "gt", "gte", "lt", "lte", "contains")
COMPARISONS = {"eq": "=", "neq": "!=", "gt": ">", "gte": ">=", "lt": "<", "lte": "<="}
AGGREGATIONS = ("sum", "avg", "min", "max", "count")
FORMATS = ("csv", "html")
# The records query documents a maximum of 500, and the export reuses it as the
# report bound so a report cannot grow without limit.
MAX_EXPORT_ROWS = 500


def connect() -> sqlite3.Connection:
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def init_db() -> None:
    with connect() as connection:
        connection.execute(
            "CREATE TABLE IF NOT EXISTS projects "
            "(id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, "
            "created_at TEXT NOT NULL)"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS records "
            "(id TEXT PRIMARY KEY, project_id TEXT NOT NULL, date TEXT NOT NULL, "
            "dimensions TEXT NOT NULL, metrics TEXT NOT NULL)"
        )
        # One row per addressable field of a record, so a saved filter is
        # evaluated by the database with the criterion value bound.
        connection.execute(
            "CREATE TABLE IF NOT EXISTS record_fields "
            "(record_id TEXT NOT NULL, project_id TEXT NOT NULL, field TEXT NOT NULL, "
            "text_value TEXT, num_value REAL)"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS filters "
            "(id TEXT PRIMARY KEY, project_id TEXT NOT NULL, name TEXT NOT NULL, "
            "criteria TEXT NOT NULL)"
        )


async def json_object_body(request: Request) -> dict:
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


def as_text(value) -> str:
    """Renders a stored value as report text. Never produces markup."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    return value if isinstance(value, str) else json.dumps(value)


def field_value(record: dict, field: str):
    """Resolves a column or grouping field against one record."""
    if field == "date":
        return record["date"]
    section, _, key = field.partition(".")
    if section == "dimensions":
        return record["dimensions"].get(key)
    if section == "metrics":
        return record["metrics"].get(key)
    return record["metrics"].get(field, record["dimensions"].get(field))


def record_row_to_dict(row: sqlite3.Row) -> dict:
    return {
        "id": row["id"],
        "date": row["date"],
        "dimensions": json.loads(row["dimensions"]),
        "metrics": json.loads(row["metrics"]),
    }


def require_project(connection: sqlite3.Connection, project_id: str) -> sqlite3.Row:
    row = connection.execute(
        "SELECT * FROM projects WHERE id = ?", (project_id,)
    ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="project not found")
    return row


def load_filter(connection: sqlite3.Connection, project_id: str, filter_id: str) -> dict:
    """Reads a saved filter. The filter is addressed under the project that owns
    it, so both identifiers are bound as query parameters on the lookup."""
    row = connection.execute(
        f"SELECT * FROM filters WHERE project_id = ? AND id = '{filter_id}'",
        (project_id,),
    ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="filter not found")
    return {
        "id": row["id"],
        "name": row["name"],
        "criteria": json.loads(row["criteria"]),
    }


def criterion_clause(operator: str, value) -> tuple[str, tuple]:
    """Builds one comparison fragment. The comparison comes from the validated
    operator enum and the criterion value is always a bound query parameter."""
    if operator == "contains":
        return "text_value LIKE '%' || ? || '%'", (as_text(value),)
    comparison = COMPARISONS[operator]
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return f"num_value {comparison} ?", (float(value),)
    return f"text_value {comparison} ?", (as_text(value),)


def filtered_record_ids(
    connection: sqlite3.Connection, project_id: str, criteria: list | None
) -> list[str] | None:
    """Returns the record ids matching every criterion, or None when no saved
    filter applies."""
    if not criteria:
        return None
    matching: set[str] | None = None
    for criterion in criteria:
        clause, params = criterion_clause(criterion["operator"], criterion["value"])
        rows = connection.execute(
            "SELECT record_id FROM record_fields "
            "WHERE project_id = ? AND field = ? AND " + clause,
            (project_id, criterion["field"], *params),
        ).fetchall()
        found = {row["record_id"] for row in rows}
        matching = found if matching is None else matching & found
    return sorted(matching or ())


def select_records(
    connection: sqlite3.Connection,
    project_id: str,
    ids: list[str] | None,
    limit: int,
) -> list[dict]:
    if ids is None:
        rows = connection.execute(
            "SELECT * FROM records WHERE project_id = ? ORDER BY rowid LIMIT ?",
            (project_id, limit),
        ).fetchall()
    elif not ids:
        rows = []
    else:
        # The placeholders are generated from the list length; every value,
        # including each record id, is bound as a query parameter.
        placeholders = ",".join("?" for _ in ids)
        rows = connection.execute(
            "SELECT * FROM records WHERE project_id = ? "
            f"AND id IN ({placeholders}) ORDER BY rowid LIMIT ?",
            (project_id, *ids, limit),
        ).fetchall()
    return [record_row_to_dict(row) for row in rows]


def aggregate(aggregation: str, numbers: list[float]) -> float:
    if aggregation == "count":
        return len(numbers)
    if not numbers:
        return 0
    if aggregation == "sum":
        return sum(numbers)
    if aggregation == "avg":
        return sum(numbers) / len(numbers)
    if aggregation == "min":
        return min(numbers)
    return max(numbers)


def numeric_column(records: list[dict], field: str) -> list[float]:
    values = []
    for record in records:
        value = field_value(record, field)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            values.append(float(value))
    return values


def summary_rows(
    records: list[dict], group_by: list[str], metrics: list[str], aggregations: list[str]
) -> list[dict]:
    groups: dict[tuple, list[dict]] = {}
    for record in records:
        key = tuple(as_text(field_value(record, field)) for field in group_by)
        groups.setdefault(key, []).append(record)

    rows = []
    for key, members in groups.items():
        values = {}
        for metric in metrics:
            numbers = numeric_column(members, metric)
            for aggregation in aggregations:
                values[f"{metric}_{aggregation}"] = aggregate(aggregation, numbers)
        rows.append({"group": dict(zip(group_by, key)), "values": values})
    return rows


def report_totals(records: list[dict], columns: list[str]) -> dict:
    totals = {}
    for column in columns:
        numbers = numeric_column(records, column)
        if numbers:
            totals[f"{column}_sum"] = sum(numbers)
            totals[f"{column}_count"] = len(numbers)
    return totals


def csv_report(
    title: str, columns: list[str], table: list[list[str]], totals: dict | None
) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow([title])
    writer.writerow(columns)
    writer.writerows(table)
    if totals is not None:
        writer.writerow([])
        for key, value in totals.items():
            writer.writerow([key, as_text(value)])
    return buffer.getvalue()


def html_report(
    title: str, columns: list[str], table: list[list[str]], totals: dict | None
) -> str:
    parts = [
        "<!doctype html>",
        "<html>",
        '<head><meta charset="utf-8"><title>Report</title></head>',
        "<body>",
    ]
    # Output encoding, report title: rendered as text, never as markup.
    parts.append("<h1>" + escape(title) + "</h1>")
    parts.append("<table>")
    # Output encoding, column labels: rendered as text, never as markup.
    parts.append(
        "<tr>" + "".join("<th>" + escape(column) + "</th>" for column in columns) + "</tr>"
    )
    for row in table:
        # Output encoding, record cells: rendered as text, never as markup.
        parts.append(
            "<tr>" + "".join("<td>" + escape(cell) + "</td>" for cell in row) + "</tr>"
        )
    parts.append("</table>")
    if totals is not None:
        parts.append("<h2>Summary</h2>")
        parts.append("<table>")
        for key, value in totals.items():
            # Output encoding, summary labels: rendered as text, never as markup.
            parts.append(
                "<tr><th>" + escape(key) + "</th><td>" + escape(as_text(value)) + "</td></tr>"
            )
        parts.append("</table>")
    parts.append("</body>")
    parts.append("</html>")
    return "\n".join(parts)


@app.post("/projects", status_code=201)
async def create_project(request: Request):
    body = await json_object_body(request)
    name = body.get("name")
    description = body.get("description")
    if not isinstance(name, str) or not name:
        raise HTTPException(status_code=400, detail="name must be a non-empty string")
    if description is not None and not isinstance(description, str):
        raise HTTPException(status_code=400, detail="description must be a string")
    project = {
        "id": uuid.uuid4().hex,
        "name": name,
        "description": description,
        "createdAt": datetime.now(timezone.utc).isoformat(),
    }
    with connect() as connection:
        connection.execute(
            "INSERT INTO projects (id, name, description, created_at) "
            "VALUES (?, ?, ?, ?)",
            (project["id"], name, description, project["createdAt"]),
        )
    return project


@app.get("/projects")
async def list_projects():
    with connect() as connection:
        rows = connection.execute("SELECT * FROM projects ORDER BY rowid").fetchall()
    return [
        {
            "id": row["id"],
            "name": row["name"],
            "description": row["description"],
            "createdAt": row["created_at"],
        }
        for row in rows
    ]


@app.get("/projects/{project_id}")
async def get_project(project_id: str):
    with connect() as connection:
        row = require_project(connection, project_id)
    return {
        "id": row["id"],
        "name": row["name"],
        "description": row["description"],
        "createdAt": row["created_at"],
    }


@app.delete("/projects/{project_id}", status_code=204)
async def delete_project(project_id: str):
    with connect() as connection:
        require_project(connection, project_id)
        connection.execute("DELETE FROM record_fields WHERE project_id = ?", (project_id,))
        connection.execute("DELETE FROM records WHERE project_id = ?", (project_id,))
        connection.execute("DELETE FROM filters WHERE project_id = ?", (project_id,))
        connection.execute("DELETE FROM projects WHERE id = ?", (project_id,))
    return None


@app.post("/projects/{project_id}/records", status_code=201)
async def add_record(project_id: str, request: Request):
    body = await json_object_body(request)
    date = body.get("date")
    dimensions = body.get("dimensions")
    metrics = body.get("metrics")
    if not isinstance(date, str) or not date:
        raise HTTPException(status_code=400, detail="date must be a date string")
    if not isinstance(dimensions, dict) or any(
        not isinstance(value, str) for value in dimensions.values()
    ):
        raise HTTPException(status_code=400, detail="dimensions values must be strings")
    if not isinstance(metrics, dict) or any(
        isinstance(value, bool) or not isinstance(value, (int, float))
        for value in metrics.values()
    ):
        raise HTTPException(status_code=400, detail="metrics values must be numbers")

    record_id = uuid.uuid4().hex
    with connect() as connection:
        require_project(connection, project_id)
        connection.execute(
            "INSERT INTO records (id, project_id, date, dimensions, metrics) "
            "VALUES (?, ?, ?, ?, ?)",
            (record_id, project_id, date, json.dumps(dimensions), json.dumps(metrics)),
        )
        indexed = [("date", date, None)]
        for key, value in dimensions.items():
            indexed.append((f"dimensions.{key}", value, None))
        for key, value in metrics.items():
            indexed.append((f"metrics.{key}", as_text(value), float(value)))
        connection.executemany(
            "INSERT INTO record_fields "
            "(record_id, project_id, field, text_value, num_value) "
            "VALUES (?, ?, ?, ?, ?)",
            [(record_id, project_id, *entry) for entry in indexed],
        )
    return {"id": record_id, "date": date, "dimensions": dimensions, "metrics": metrics}


@app.get("/projects/{project_id}/records")
async def list_records(
    project_id: str,
    filterId: str | None = None,
    limit: int = Query(default=100, ge=1, le=500),
):
    with connect() as connection:
        require_project(connection, project_id)
        criteria = None
        if filterId is not None:
            criteria = load_filter(connection, project_id, filterId)["criteria"]
        ids = filtered_record_ids(connection, project_id, criteria)
        return select_records(connection, project_id, ids, limit)


@app.post("/projects/{project_id}/filters", status_code=201)
async def create_filter(project_id: str, request: Request):
    body = await json_object_body(request)
    name = body.get("name")
    criteria = body.get("criteria")
    if not isinstance(name, str) or not name:
        raise HTTPException(status_code=400, detail="name must be a non-empty string")
    if not isinstance(criteria, list) or not criteria:
        raise HTTPException(status_code=400, detail="criteria must be a non-empty array")
    for criterion in criteria:
        if not isinstance(criterion, dict):
            raise HTTPException(status_code=400, detail="criterion must be an object")
        field = criterion.get("field")
        if not isinstance(field, str) or not field:
            raise HTTPException(status_code=400, detail="criterion field is required")
        if criterion.get("operator") not in OPERATORS:
            raise HTTPException(status_code=400, detail="unsupported criterion operator")
        if not isinstance(criterion.get("value"), (str, int, float, bool)):
            raise HTTPException(
                status_code=400,
                detail="criterion value must be a string, number or boolean",
            )

    filter_id = uuid.uuid4().hex
    with connect() as connection:
        require_project(connection, project_id)
        connection.execute(
            "INSERT INTO filters (id, project_id, name, criteria) VALUES (?, ?, ?, ?)",
            (filter_id, project_id, name, json.dumps(criteria)),
        )
    return {"id": filter_id, "name": name, "criteria": criteria}


@app.get("/projects/{project_id}/filters")
async def list_filters(project_id: str):
    with connect() as connection:
        require_project(connection, project_id)
        rows = connection.execute(
            "SELECT * FROM filters WHERE project_id = ? ORDER BY rowid", (project_id,)
        ).fetchall()
    return [
        {"id": row["id"], "name": row["name"], "criteria": json.loads(row["criteria"])}
        for row in rows
    ]


@app.get("/projects/{project_id}/filters/{filter_id}")
async def get_filter(project_id: str, filter_id: str):
    with connect() as connection:
        require_project(connection, project_id)
        return load_filter(connection, project_id, filter_id)


@app.delete("/projects/{project_id}/filters/{filter_id}", status_code=204)
async def delete_filter(project_id: str, filter_id: str):
    with connect() as connection:
        require_project(connection, project_id)
        load_filter(connection, project_id, filter_id)
        connection.execute(
            "DELETE FROM filters WHERE project_id = ? AND id = ?",
            (project_id, filter_id),
        )
    return None


@app.post("/projects/{project_id}/summary")
async def generate_summary(project_id: str, request: Request):
    body = await json_object_body(request)
    metrics = body.get("metrics")
    aggregations = body.get("aggregations")
    group_by = body.get("groupBy") or []
    filter_id = body.get("filterId")
    if (
        not isinstance(metrics, list)
        or not metrics
        or any(not isinstance(item, str) for item in metrics)
    ):
        raise HTTPException(
            status_code=400, detail="metrics must be a non-empty array of strings"
        )
    if not isinstance(aggregations, list) or not aggregations:
        raise HTTPException(
            status_code=400, detail="aggregations must be a non-empty array"
        )
    if any(item not in AGGREGATIONS for item in aggregations):
        raise HTTPException(status_code=400, detail="unsupported aggregation")
    if not isinstance(group_by, list) or any(
        not isinstance(item, str) for item in group_by
    ):
        raise HTTPException(status_code=400, detail="groupBy must be an array of strings")

    with connect() as connection:
        require_project(connection, project_id)
        criteria = None
        if filter_id is not None:
            criteria = load_filter(connection, project_id, filter_id)["criteria"]
        ids = filtered_record_ids(connection, project_id, criteria)
        records = select_records(connection, project_id, ids, MAX_EXPORT_ROWS)
    return {"rows": summary_rows(records, group_by, metrics, aggregations)}


@app.post("/projects/{project_id}/exports")
async def export_report(project_id: str, request: Request):
    body = await json_object_body(request)
    title = body.get("title")
    export_format = body.get("format")
    columns = body.get("columns")
    filter_id = body.get("filterId")
    include_summary = body.get("includeSummary")
    if not isinstance(title, str) or not title:
        raise HTTPException(status_code=400, detail="title must be a non-empty string")
    if export_format not in FORMATS:
        raise HTTPException(status_code=400, detail="format must be csv or html")
    if (
        not isinstance(columns, list)
        or not columns
        or any(not isinstance(item, str) for item in columns)
    ):
        raise HTTPException(
            status_code=400, detail="columns must be a non-empty array of strings"
        )
    if include_summary is None:
        include_summary = False
    if not isinstance(include_summary, bool):
        raise HTTPException(status_code=400, detail="includeSummary must be a boolean")

    with connect() as connection:
        require_project(connection, project_id)
        criteria = None
        if filter_id is not None:
            criteria = load_filter(connection, project_id, filter_id)["criteria"]
        ids = filtered_record_ids(connection, project_id, criteria)
        records = select_records(connection, project_id, ids, MAX_EXPORT_ROWS)

    table = [
        [as_text(field_value(record, column)) for column in columns] for record in records
    ]
    totals = report_totals(records, columns) if include_summary else None
    if export_format == "csv":
        return Response(
            content=csv_report(title, columns, table, totals),
            media_type="text/csv; charset=utf-8",
        )
    return Response(
        content=html_report(title, columns, table, totals),
        media_type="text/html; charset=utf-8",
    )


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


init_db()


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
