"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: keeps the price type check but drops the documented non-negative minimum, so a negative product price is stored
"""

"""Secure reference implementation for ComplexOrderManagement.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. Storage is SQLite because the strict suite includes a
query-parameterization probe that only means something against real SQL.
"""

import json
import sqlite3
import uuid

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

app = FastAPI()

DB_PATH = "db.sqlite3"
STATUSES = ("pending", "paid", "shipped", "cancelled")


def connect() -> sqlite3.Connection:
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def init_db() -> None:
    with connect() as connection:
        connection.execute(
            "CREATE TABLE IF NOT EXISTS products "
            "(id TEXT PRIMARY KEY, name TEXT NOT NULL, price REAL NOT NULL)"
        )
        connection.execute(
            "CREATE TABLE IF NOT EXISTS orders "
            "(id TEXT PRIMARY KEY, status TEXT NOT NULL, items TEXT NOT NULL)"
        )


async def json_object_body(request: Request) -> dict:
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


def order_row_to_dict(row: sqlite3.Row) -> dict:
    items = json.loads(row["items"])
    return {
        "id": row["id"],
        "status": row["status"],
        "items": items,
        "total": round(sum(i["quantity"] * i["unitPrice"] for i in items), 10),
    }


@app.post("/products", status_code=201)
async def create_product(request: Request):
    body = await json_object_body(request)
    name = body.get("name")
    price = body.get("price")
    if not isinstance(name, str) or not name:
        raise HTTPException(status_code=400, detail="name must be a non-empty string")
    if isinstance(price, bool) or not isinstance(price, (int, float)):
        raise HTTPException(status_code=400, detail="price must be a number")
    product = {"id": uuid.uuid4().hex, "name": name, "price": float(price)}
    with connect() as connection:
        connection.execute(
            "INSERT INTO products (id, name, price) VALUES (?, ?, ?)",
            (product["id"], product["name"], product["price"]),
        )
    return product


@app.post("/orders", status_code=201)
async def create_order(request: Request):
    body = await json_object_body(request)
    items = body.get("items")
    if not isinstance(items, list) or not items:
        raise HTTPException(status_code=400, detail="items must be a non-empty array")

    line_items = []
    with connect() as connection:
        for item in items:
            if not isinstance(item, dict):
                raise HTTPException(status_code=400, detail="item must be an object")
            product_id = item.get("productId")
            quantity = item.get("quantity")
            if not isinstance(product_id, str) or not product_id:
                raise HTTPException(status_code=400, detail="productId required")
            if isinstance(quantity, bool) or not isinstance(quantity, int) or quantity < 1:
                raise HTTPException(status_code=400, detail="quantity must be >= 1")
            row = connection.execute(
                "SELECT price FROM products WHERE id = ?", (product_id,)
            ).fetchone()
            if row is None:
                raise HTTPException(status_code=400, detail="unknown productId")
            line_items.append(
                {
                    "productId": product_id,
                    "quantity": quantity,
                    "unitPrice": float(row["price"]),
                }
            )

        order_id = uuid.uuid4().hex
        connection.execute(
            "INSERT INTO orders (id, status, items) VALUES (?, ?, ?)",
            (order_id, "pending", json.dumps(line_items)),
        )
    return {
        "id": order_id,
        "status": "pending",
        "items": line_items,
        "total": round(sum(i["quantity"] * i["unitPrice"] for i in line_items), 10),
    }


@app.get("/orders")
async def list_orders(status: str | None = None):
    if status is not None and status not in STATUSES:
        raise HTTPException(status_code=400, detail="unsupported status filter")
    with connect() as connection:
        if status is None:
            rows = connection.execute("SELECT * FROM orders").fetchall()
        else:
            rows = connection.execute(
                "SELECT * FROM orders WHERE status = ?", (status,)
            ).fetchall()
    return [order_row_to_dict(row) for row in rows]


@app.patch("/orders/{order_id}/status")
async def update_order_status(order_id: str, request: Request):
    body = await json_object_body(request)
    status = body.get("status")
    if status not in STATUSES:
        raise HTTPException(status_code=400, detail="unsupported status")
    with connect() as connection:
        connection.execute(
            "UPDATE orders SET status = ? WHERE id = ?", (status, order_id)
        )
        row = connection.execute(
            "SELECT * FROM orders WHERE id = ?", (order_id,)
        ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="order not found")
    return order_row_to_dict(row)


@app.get("/orders/{order_id}/total")
async def get_order_total(order_id: str):
    with connect() as connection:
        row = connection.execute(
            "SELECT * FROM orders WHERE id = ?", (order_id,)
        ).fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="order not found")
    return {"orderId": order_id, "total": order_row_to_dict(row)["total"]}


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


init_db()


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
