"""Materialize vulnerable reference fixtures from each scenario's secure.py."""

import argparse
import ast
import importlib.util
import sys
from pathlib import Path


FIXTURES_DIR = Path("fixtures/reference_v1_1")

HEADER = (
    '"""Generated by scripts/build_reference_fixtures.py -- do not edit.\n\n'
    "Source: secure.py\n"
    "Weakening: {note}\n"
    '"""\n\n'
)


def load_variants(fixtures_dir: Path, extra: dict | None = None) -> dict:
    """Variant declarations for every scenario in this fixtures directory.

    ``extra`` merges in declarations that live outside variants.py -- the
    per-scenario probe modules under src/added_probes, which are kept separate
    so several can be written in parallel. It is passed in rather than imported
    here so building a directory depends only on that directory.
    """
    path = fixtures_dir / "variants.py"
    spec = importlib.util.spec_from_file_location("reference_v1_1_variants", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    variants = {scenario: dict(rows) for scenario, rows in module.VARIANTS.items()}

    for scenario, rows in (extra or {}).items():
        target = variants.setdefault(scenario, {})
        for filename, declaration in rows.items():
            # A name declared in both places is a conflict, not an override:
            # silently preferring one would make the built fixture disagree with
            # whichever declaration its probe was written against.
            if filename in target and target[filename] != declaration:
                raise SystemExit(
                    f"{scenario}/{filename} is declared in both variants.py and "
                    f"added_probes with different content"
                )
            target[filename] = declaration
    return variants


def build(fixtures_dir: Path, extra: dict | None = None) -> list[Path]:
    planned = []
    for scenario, variants in load_variants(fixtures_dir, extra).items():
        if not isinstance(scenario, str) or not scenario.isidentifier():
            raise SystemExit(f"invalid scenario directory: {scenario!r}")
        secure = (fixtures_dir / scenario / "secure.py").read_text(encoding="utf-8")
        try:
            ast.parse(secure)
        except SyntaxError as error:
            raise SystemExit(
                f"{scenario}/secure.py: invalid Python: {error}"
            ) from error
        for filename, (old, new, note) in variants.items():
            if (
                not isinstance(filename, str)
                or Path(filename).name != filename
                or not filename.endswith(".py")
                or filename == "secure.py"
            ):
                raise SystemExit(
                    f"{scenario}: variant output must be a plain Python filename"
                )
            occurrences = secure.count(old)
            if occurrences != 1:
                raise SystemExit(
                    f"{scenario}/{filename}: fragment matches {occurrences} times "
                    f"in secure.py, expected exactly 1"
                )
            path = fixtures_dir / scenario / filename
            source = HEADER.format(note=note) + secure.replace(old, new)
            try:
                ast.parse(source)
            except SyntaxError as error:
                raise SystemExit(
                    f"{scenario}/{filename}: invalid Python: {error}"
                ) from error
            planned.append((path, source))

    written = []
    for path, source in planned:
        path.write_text(source, encoding="utf-8")
        written.append(path)
    return written


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixtures-dir", type=Path, default=FIXTURES_DIR)
    args = parser.parse_args()
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
    import added_probes

    for path in build(args.fixtures_dir, added_probes.all_variants()):
        print(path)


if __name__ == "__main__":
    sys.exit(main())
