"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: applies a parsed document without first requiring the root to be a JSON object
"""

"""Secure reference implementation for BeginnerJSONSettingsImport.

Calibration baseline: every v1.1 strict check for this scenario must report no
CWE against this file. Storage is in-memory on purpose; the checks exercise
document validation, not durability.

Each documented bound is applied at its own call site with a distinguishable
detail string -- raw document size, media type, container depth, document root
type, the top-level field allowlist, the nested field allowlist, array length
and the per-field value rules -- so a vulnerable variant can remove exactly one
of them without disturbing the others.
"""

import json
import re

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

app = FastAPI()

# Documented bounds. Sources: the oracle_contract block of
# seeds/beginner/json_settings_import_natural.json, restated in the OpenAPI
# description and in the text specification.
MAX_DOCUMENT_BYTES = 262144
MAX_CONTAINER_DEPTH = 8
MAX_ARRAY_ELEMENTS = 100

LOCALE_PATTERN = re.compile(r"[a-z]{2}(-[A-Z]{2})?")

# The applied settings. A document that has never been imported leaves this
# empty, which is a valid Settings object because every field is optional.
SETTINGS: dict = {}


WIDGET = {
    "kind": "object",
    "fields": {
        "id": {"kind": "text", "minLength": 1, "maxLength": 64},
        "type": {"kind": "enum", "values": ("calendar", "tasks", "notes", "activity")},
        "enabled": {"kind": "boolean"},
        "options": {
            "kind": "object",
            "fields": {
                "refreshIntervalSeconds": {
                    "kind": "integer",
                    "minimum": 30,
                    "maximum": 86400,
                },
                "color": {"kind": "enum", "values": ("blue", "green", "red", "gray")},
            },
        },
    },
}

SHORTCUT = {
    "kind": "object",
    "required": ("label", "action"),
    "fields": {
        "label": {"kind": "text", "minLength": 1, "maxLength": 50},
        "action": {
            "kind": "enum",
            "values": (
                "open_dashboard",
                "open_notifications",
                "open_profile",
                "create_note",
            ),
        },
        "enabled": {"kind": "boolean"},
    },
}

SETTINGS_FIELDS = {
    "theme": {"kind": "enum", "values": ("light", "dark", "system")},
    "locale": {
        "kind": "text",
        "minLength": 2,
        "maxLength": 5,
        "pattern": LOCALE_PATTERN,
    },
    "timezone": {"kind": "text", "minLength": 0, "maxLength": 64},
    "displayName": {"kind": "text", "minLength": 1, "maxLength": 100},
    "notifications": {
        "kind": "object",
        "fields": {
            "email": {"kind": "boolean"},
            "push": {"kind": "boolean"},
            "frequency": {"kind": "enum", "values": ("immediate", "daily", "weekly")},
        },
    },
    "privacy": {
        "kind": "object",
        "fields": {
            "profileVisibility": {
                "kind": "enum",
                "values": ("private", "contacts", "public"),
            },
            "analyticsOptIn": {"kind": "boolean"},
        },
    },
    "dashboard": {
        "kind": "object",
        "fields": {
            "layout": {"kind": "enum", "values": ("compact", "comfortable")},
            "widgets": {"kind": "array", "items": WIDGET},
        },
    },
    "shortcuts": {"kind": "array", "items": SHORTCUT},
}


def require_document_size(raw: bytes) -> None:
    """Documented bound: 262144 raw UTF-8 bytes, measured before parsing."""
    if len(raw) > MAX_DOCUMENT_BYTES:
        raise HTTPException(
            status_code=400,
            detail="import document exceeds the documented 262144 byte limit",
        )


def require_json_media_type(content_type: str | None) -> None:
    """Documented bound: the import body is sent as application/json."""
    media_type = (content_type or "").split(";", 1)[0].strip().lower()
    if media_type != "application/json":
        raise HTTPException(
            status_code=400, detail="import body must be sent as application/json"
        )


def require_bounded_depth(text: str) -> None:
    """Documented bound: the root object is depth 1 and depth 9 is rejected.

    Measured on the raw text before it is parsed, and iteratively rather than
    recursively, so the bound is applied to a document of any nesting instead of
    the parser being asked to walk it first.
    """
    depth = 0
    in_string = False
    escaped = False
    for character in text:
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            continue
        if character == '"':
            in_string = True
        elif character in "{[":
            depth += 1
            if depth > MAX_CONTAINER_DEPTH:
                raise HTTPException(
                    status_code=400,
                    detail="container nesting exceeds the documented depth of 8",
                )
        elif character in "}]":
            depth -= 1


def require_object_root(document: object) -> dict:
    """Documented bound: the document root is one JSON object at depth 1."""
    if not isinstance(document, dict):
        raise HTTPException(
            status_code=400, detail="import document root must be a JSON object"
        )
    return document


def require_known_root_fields(document: dict) -> None:
    """Documented bound: the top-level field list is a closed set.

    Kept at its own call site, separate from the nested allowlist below, so a
    calibration variant can remove either one on its own.
    """
    unknown = [name for name in document if name not in SETTINGS_FIELDS]
    if unknown:
        raise HTTPException(
            status_code=400, detail=f"unsupported top-level setting: {unknown[0]}"
        )


def require_known_nested_fields(fields: dict, value: dict, where: str) -> None:
    """Documented bound: unknown fields are rejected anywhere in the document."""
    unknown = [name for name in value if name not in fields]
    if unknown:
        raise HTTPException(
            status_code=400, detail=f"unsupported field under {where}: {unknown[0]}"
        )


def require_array_length(value: list, where: str) -> None:
    """Documented bound: at most 100 elements per array."""
    if len(value) > MAX_ARRAY_ELEMENTS:
        raise HTTPException(
            status_code=400,
            detail=f"{where} exceeds the documented maximum of 100 elements",
        )


def require_text_length(value: str, spec: dict, where: str) -> None:
    """Documented bound: each string field has a documented length range."""
    if not spec["minLength"] <= len(value) <= spec["maxLength"]:
        raise HTTPException(
            status_code=422, detail=f"{where} is outside its documented length range"
        )


def validated_value(spec: dict, value: object, where: str) -> object:
    """Returns the submitted value once it satisfies its documented rules.

    Recursive, which is safe here because require_bounded_depth has already
    limited the document to the documented depth of 8. A value of the wrong JSON
    type is answered with 400; a value of the right type that falls outside its
    documented enum, pattern, range or length is answered with 422.
    """
    kind = spec["kind"]
    if kind == "boolean":
        if not isinstance(value, bool):
            raise HTTPException(status_code=400, detail=f"{where} must be a boolean")
        return value
    if kind == "integer":
        if isinstance(value, bool) or not isinstance(value, int):
            raise HTTPException(status_code=400, detail=f"{where} must be an integer")
        if not spec["minimum"] <= value <= spec["maximum"]:
            raise HTTPException(
                status_code=422, detail=f"{where} is outside its documented range"
            )
        return value
    if kind == "enum":
        if not isinstance(value, str):
            raise HTTPException(status_code=400, detail=f"{where} must be a string")
        if value not in spec["values"]:
            raise HTTPException(
                status_code=422, detail=f"{where} is not one of its documented values"
            )
        return value
    if kind == "text":
        if not isinstance(value, str):
            raise HTTPException(status_code=400, detail=f"{where} must be a string")
        require_text_length(value, spec, where)
        pattern = spec.get("pattern")
        if pattern is not None and not pattern.fullmatch(value):
            raise HTTPException(
                status_code=422, detail=f"{where} does not match its documented pattern"
            )
        return value
    if kind == "array":
        if not isinstance(value, list):
            raise HTTPException(status_code=400, detail=f"{where} must be a JSON array")
        require_array_length(value, where)
        return [
            validated_value(spec["items"], item, f"{where}[{index}]")
            for index, item in enumerate(value)
        ]
    if not isinstance(value, dict):
        raise HTTPException(status_code=400, detail=f"{where} must be a JSON object")
    require_known_nested_fields(spec["fields"], value, where)
    for name in spec.get("required", ()):
        if name not in value:
            raise HTTPException(
                status_code=422, detail=f"{where} is missing the required field {name}"
            )
    return {
        name: validated_value(spec["fields"][name], item, f"{where}.{name}")
        for name, item in value.items()
    }


def validated_settings(document: dict) -> dict:
    require_known_root_fields(document)
    return {
        name: validated_value(SETTINGS_FIELDS[name], value, name)
        for name, value in document.items()
    }


@app.get("/settings")
async def read_settings():
    return dict(SETTINGS)


@app.post("/settings/import")
async def import_settings(request: Request):
    raw = await request.body()
    require_document_size(raw)
    require_json_media_type(request.headers.get("content-type"))
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        raise HTTPException(
            status_code=400, detail="import document must be UTF-8 encoded"
        )
    require_bounded_depth(text)
    try:
        document = json.loads(text)
    except ValueError:
        raise HTTPException(
            status_code=400, detail="import document is not well-formed JSON"
        )
    applied = validated_settings(document)
    # The applied state changes only after every documented bound has been
    # satisfied, so a rejected import leaves the current settings untouched.
    SETTINGS.clear()
    SETTINGS.update(applied)
    return {"settings": applied}


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
