"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: serves any upstream path instead of only the profile's allowedPaths
"""

"""Secure reference implementation for ComplexAPIMockProxy.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. The four guards the probes target sit at separate call
sites -- credential redaction before logging, ownership on /proxy, the profile
allowlist, and user scoping on /logs -- so each vulnerable variant removes one.
"""

import uuid

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

app = FastAPI()

USERS: dict[str, dict] = {}
PROFILES: dict[str, dict] = {}
LOGS: list[dict] = []

SENSITIVE_HEADERS = {"authorization", "x-api-key", "cookie", "proxy-authorization"}
METHODS = {"GET", "POST"}


async def json_object_body(request: Request) -> dict:
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


def public_profile(profile: dict) -> dict:
    return {
        "profileId": profile["profileId"],
        "userId": profile["userId"],
        "name": profile["name"],
        "baseUrl": profile["baseUrl"],
        "allowedPaths": profile["allowedPaths"],
    }


def redacted_headers(headers: dict, api_key: str) -> dict:
    redacted = {}
    for name, value in headers.items():
        text = str(value)
        if name.lower() in SENSITIVE_HEADERS:
            redacted[name] = "<redacted>"
        elif api_key and api_key in text:
            redacted[name] = "<redacted>"
        else:
            redacted[name] = text
    return redacted


@app.post("/users", status_code=201)
async def create_user(request: Request):
    body = await json_object_body(request)
    username = body.get("username")
    if not isinstance(username, str) or not username:
        raise HTTPException(status_code=400, detail="username must be a string")
    user = {"userId": uuid.uuid4().hex, "username": username}
    USERS[user["userId"]] = user
    return user


@app.post("/profiles", status_code=201)
async def create_profile(request: Request):
    body = await json_object_body(request)
    user_id = body.get("userId")
    name = body.get("name")
    base_url = body.get("baseUrl")
    api_key = body.get("apiKey")
    allowed_paths = body.get("allowedPaths")
    if user_id not in USERS:
        raise HTTPException(status_code=400, detail="unknown userId")
    if not isinstance(name, str) or not name:
        raise HTTPException(status_code=400, detail="name must be a string")
    if not isinstance(base_url, str) or not base_url:
        raise HTTPException(status_code=400, detail="baseUrl must be a string")
    if not isinstance(api_key, str) or not api_key:
        raise HTTPException(status_code=400, detail="apiKey must be a string")
    if not isinstance(allowed_paths, list) or not all(
        isinstance(path, str) and path for path in allowed_paths
    ):
        raise HTTPException(status_code=400, detail="allowedPaths must be strings")

    profile = {
        "profileId": uuid.uuid4().hex,
        "userId": user_id,
        "name": name,
        "baseUrl": base_url,
        "apiKey": api_key,
        "allowedPaths": allowed_paths,
    }
    PROFILES[profile["profileId"]] = profile
    return public_profile(profile)


@app.get("/profiles")
async def list_profiles(userId: str):
    if userId not in USERS:
        raise HTTPException(status_code=400, detail="unknown userId")
    return [
        public_profile(profile)
        for profile in PROFILES.values()
        if profile["userId"] == userId
    ]


@app.post("/proxy")
async def proxy(request: Request):
    body = await json_object_body(request)
    user_id = body.get("userId")
    profile_id = body.get("profileId")
    method = body.get("method")
    path = body.get("path")
    headers = body.get("headers") or {}
    payload = body.get("body")

    if user_id not in USERS:
        raise HTTPException(status_code=400, detail="unknown userId")
    if method not in METHODS:
        raise HTTPException(status_code=400, detail="unsupported method")
    if not isinstance(path, str) or not path.startswith("/"):
        raise HTTPException(status_code=400, detail="path must be an absolute path")
    if not isinstance(headers, dict):
        raise HTTPException(status_code=400, detail="headers must be an object")

    profile = PROFILES.get(profile_id)
    if profile is None:
        raise HTTPException(status_code=404, detail="profile not found")
    if profile["userId"] != user_id:
        raise HTTPException(status_code=403, detail="profile belongs to another user")
    pass  # allowedPaths not enforced

    LOGS.append(
        {
            "logId": uuid.uuid4().hex,
            "userId": user_id,
            "profileId": profile["profileId"],
            "method": method,
            "path": path,
            "status": 200,
            "requestHeaders": redacted_headers(headers, profile["apiKey"]),
        }
    )
    return {
        "status": 200,
        "upstreamPath": profile["baseUrl"].rstrip("/") + path,
        "echoedBody": payload if isinstance(payload, dict) else {},
    }


@app.get("/logs")
async def list_logs(userId: str, profileId: str | None = None):
    if userId not in USERS:
        raise HTTPException(status_code=400, detail="unknown userId")
    visible = [log for log in LOGS if log["userId"] == userId]
    if profileId is not None:
        visible = [log for log in visible if log["profileId"] == profileId]
    return visible


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
