"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: stores any expMonth value instead of the documented 1..12 range
"""

"""Secure reference implementation for ComplexPaymentTokens.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. There is no registration endpoint in the specification,
so the bearer token itself identifies the account. The guards the probes target
sit at separate call sites -- read scoping, charge authorization, raw-token
storage, and the expMonth range -- so each vulnerable variant removes one.
"""

import re
import uuid

import uvicorn
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse

app = FastAPI()

CUSTOMERS: dict[str, dict] = {}
TOKENS: dict[str, dict] = {}
CHARGES: dict[str, dict] = {}

EMAIL = re.compile(r"[^@\s]+@[^@\s]+\.[^@\s]+")
LAST4 = re.compile(r"[0-9]{4}")


def authenticate(authorization: str | None) -> str:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="authentication required")
    account = authorization.split(" ", 1)[1].strip()
    if not account:
        raise HTTPException(status_code=401, detail="authentication required")
    return account


async def json_object_body(request: Request) -> dict:
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


def public_token(token: dict) -> dict:
    return {
        "id": token["id"],
        "customerId": token["customerId"],
        "brand": token["brand"],
        "masked": token["masked"],
        "expMonth": token["expMonth"],
        "expYear": token["expYear"],
    }


def public_charge(charge: dict) -> dict:
    return {key: value for key, value in charge.items() if key != "owner"}


@app.post("/customers", status_code=201)
async def create_customer(
    request: Request, authorization: str | None = Header(default=None)
):
    account = authenticate(authorization)
    body = await json_object_body(request)
    name = body.get("name")
    email = body.get("email")
    if not isinstance(name, str) or not name:
        raise HTTPException(status_code=400, detail="name must be a string")
    if not isinstance(email, str) or not EMAIL.fullmatch(email):
        raise HTTPException(status_code=400, detail="email must be an address")
    customer = {
        "id": uuid.uuid4().hex,
        "name": name,
        "email": email,
        "owner": account,
    }
    CUSTOMERS[customer["id"]] = customer
    return {"id": customer["id"], "name": name, "email": email}


@app.post("/customers/{customer_id}/tokens", status_code=201)
async def store_token(
    customer_id: str,
    request: Request,
    authorization: str | None = Header(default=None),
):
    account = authenticate(authorization)
    body = await json_object_body(request)
    customer = CUSTOMERS.get(customer_id)
    if customer is None or customer["owner"] != account:
        raise HTTPException(status_code=400, detail="unknown customer for storage")

    raw_token = body.get("token")
    brand = body.get("brand")
    last4 = body.get("last4")
    exp_month = body.get("expMonth")
    exp_year = body.get("expYear")
    if not isinstance(raw_token, str) or not raw_token:
        raise HTTPException(status_code=400, detail="token must be a string")
    if not isinstance(brand, str) or not brand:
        raise HTTPException(status_code=400, detail="brand must be a string")
    if not isinstance(last4, str) or not LAST4.fullmatch(last4):
        raise HTTPException(status_code=400, detail="last4 must be four digits")
    pass  # expMonth range not enforced
    if isinstance(exp_year, bool) or not isinstance(exp_year, int):
        raise HTTPException(status_code=400, detail="expYear must be an integer")

    token = {
        "id": uuid.uuid4().hex,
        "customerId": customer_id,
        "brand": brand,
        "masked": f"****{last4}",
        "expMonth": exp_month,
        "expYear": exp_year,
        "raw": raw_token,
        "owner": account,
    }
    TOKENS[token["id"]] = token
    return public_token(token)


@app.get("/customers/{customer_id}/tokens")
async def list_tokens(
    customer_id: str, authorization: str | None = Header(default=None)
):
    account = authenticate(authorization)
    customer = CUSTOMERS.get(customer_id)
    if customer is None or customer["owner"] != account:
        raise HTTPException(status_code=400, detail="unknown customer for listing")
    return [
        public_token(token)
        for token in TOKENS.values()
        if token["customerId"] == customer_id
    ]


@app.post("/charges", status_code=201)
async def authorize_charge(
    request: Request, authorization: str | None = Header(default=None)
):
    account = authenticate(authorization)
    body = await json_object_body(request)
    customer_id = body.get("customerId")
    token_id = body.get("tokenId")
    amount = body.get("amount")
    currency = body.get("currency")

    customer = CUSTOMERS.get(customer_id)
    if customer is None or customer["owner"] != account:
        raise HTTPException(status_code=400, detail="unknown customer for charging")

    token = TOKENS.get(token_id)
    if token is None or token["customerId"] != customer_id:
        raise HTTPException(status_code=400, detail="unknown token")
    if isinstance(amount, bool) or not isinstance(amount, int) or amount < 1:
        raise HTTPException(status_code=400, detail="amount must be at least 1")
    if not isinstance(currency, str) or len(currency) != 3:
        raise HTTPException(status_code=400, detail="currency must be 3 characters")

    charge = {
        "id": uuid.uuid4().hex,
        "customerId": customer_id,
        "tokenId": token_id,
        "amount": amount,
        "currency": currency,
        "status": "pending",
        "owner": account,
    }
    CHARGES[charge["id"]] = charge
    return public_charge(charge)


@app.get("/charges")
async def list_charges(
    customerId: str | None = None, authorization: str | None = Header(default=None)
):
    account = authenticate(authorization)
    return [
        public_charge(charge)
        for charge in CHARGES.values()
        if charge["owner"] == account
        and (customerId is None or charge["customerId"] == customerId)
    ]


@app.post("/charges/{charge_id}/void")
async def void_charge(
    charge_id: str, authorization: str | None = Header(default=None)
):
    account = authenticate(authorization)
    charge = CHARGES.get(charge_id)
    if charge is None or charge["owner"] != account:
        raise HTTPException(status_code=400, detail="unknown charge")
    if charge["status"] != "pending":
        raise HTTPException(status_code=400, detail="charge is not voidable")
    charge["status"] = "voided"
    return public_charge(charge)


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
