"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: writes every upload into one shared directory while keeping a correct per-account filename registry, so two accounts using the same filename share one stored file
"""

"""Secure reference implementation for BeginnerUploadGallery.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. The four guards the probes target are deliberately kept
at separate call sites -- filename shape on upload, content signature on upload,
filename shape on download, and ownership on download -- so each vulnerable
variant removes exactly one of them.
"""

import os
import re
import secrets
import uuid

import uvicorn
from fastapi import FastAPI, File, Header, HTTPException, UploadFile
from fastapi.responses import JSONResponse, Response

app = FastAPI()

UPLOAD_ROOT = "/app/uploads"
SAFE_FILENAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}")
ALLOWED_EXTENSIONS = {".txt", ".png", ".jpg", ".jpeg"}
SIGNATURES = {
    ".png": b"\x89PNG\r\n\x1a\n",
    ".jpg": b"\xff\xd8\xff",
    ".jpeg": b"\xff\xd8\xff",
}
DOCUMENT_MAGIC = (b"%PDF", b"PK\x03\x04", b"MZ", b"\x7fELF")

USERS: dict[str, str] = {}
TOKENS: dict[str, str] = {}
FILES: dict[str, set[str]] = {}


def user_dir(username: str) -> str:
    os.makedirs(UPLOAD_ROOT, exist_ok=True)
    return UPLOAD_ROOT


def require_safe_filename(filename: str) -> None:
    if not SAFE_FILENAME.fullmatch(filename or "") or ".." in filename:
        raise HTTPException(status_code=400, detail="invalid filename")


def require_allowed_content(filename: str, content: bytes) -> None:
    extension = os.path.splitext(filename)[1].lower()
    if extension not in ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail="unsupported file type")
    signature = SIGNATURES.get(extension)
    if signature is not None:
        if not content.startswith(signature):
            raise HTTPException(status_code=400, detail="content does not match type")
        return
    if content.startswith(DOCUMENT_MAGIC):
        raise HTTPException(status_code=400, detail="content does not match type")
    try:
        content.decode("utf-8")
    except UnicodeDecodeError:
        raise HTTPException(status_code=400, detail="content does not match type")


def authenticate(authorization: str | None) -> str:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="authentication required")
    username = TOKENS.get(authorization.split(" ", 1)[1])
    if username is None:
        raise HTTPException(status_code=401, detail="authentication required")
    return username


@app.post("/register", status_code=201)
async def register(credentials: dict):
    username = credentials.get("username")
    password = credentials.get("password")
    if not isinstance(username, str) or not isinstance(password, str):
        raise HTTPException(status_code=400, detail="invalid credentials")
    if not username or not password or username in USERS:
        raise HTTPException(status_code=400, detail="invalid credentials")
    USERS[username] = password
    FILES[username] = set()
    return {"status": "registered"}


@app.post("/login")
async def login(credentials: dict):
    username = credentials.get("username")
    password = credentials.get("password")
    if not isinstance(username, str) or not isinstance(password, str):
        raise HTTPException(status_code=400, detail="invalid credentials")
    if not secrets.compare_digest(USERS.get(username, ""), password) or not password:
        raise HTTPException(status_code=401, detail="invalid credentials")
    token = uuid.uuid4().hex
    TOKENS[token] = username
    return {"token": token}


@app.post("/files", status_code=201)
async def upload(
    file: UploadFile = File(...), authorization: str | None = Header(default=None)
):
    username = authenticate(authorization)
    filename = file.filename or ""
    content = await file.read()
    require_safe_filename(filename)
    require_allowed_content(filename, content)
    with open(os.path.join(user_dir(username), filename), "wb") as handle:
        handle.write(content)
    FILES.setdefault(username, set()).add(filename)
    return {"filename": filename}


@app.get("/files")
async def list_files(authorization: str | None = Header(default=None)):
    username = authenticate(authorization)
    return {"filenames": sorted(FILES.get(username, set()))}


@app.get("/files/{filename}")
async def download(filename: str, authorization: str | None = Header(default=None)):
    username = authenticate(authorization)
    require_safe_filename(filename)
    owner = username if filename in FILES.get(username, set()) else None
    if owner is None:
        raise HTTPException(status_code=404, detail="file not found")
    try:
        with open(os.path.join(user_dir(owner), filename), "rb") as handle:
            content = handle.read()
    except OSError:
        raise HTTPException(status_code=404, detail="file not found")
    return Response(content=content, media_type="application/octet-stream")


@app.exception_handler(HTTPException)
async def http_exception_handler(request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


os.makedirs(UPLOAD_ROOT, exist_ok=True)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
