"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: builds a Python expression from the filter value and evaluates it, instead of comparing the value as data; this is the deliberate defect the scenario's CWE-94 check is calibrated to detect
"""

"""Secure reference implementation for BeginnerCSVFilter.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. The CSV text is written into a datasets directory on
disk, because the strict suite includes a path-traversal probe that only means
something against real files; the small per-dataset record is kept in memory,
since the probes exercise request validation rather than durability.
"""

import csv
import io
import os
import re

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse, Response

app = FastAPI()

DATA_DIR = os.path.abspath("datasets")
SAFE_DATASET_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9_.-]{0,63}")
EXTRA_FIELDS = "__extra__"

# The specification asks for bounded input without fixing a number, so these
# are reference limits, wide enough for the documented example datasets.
MAX_CSV_BYTES = 1024 * 1024
MAX_ROWS = 10000

DATASETS: dict[str, dict] = {}


async def json_object_body(request: Request) -> dict:
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


def require_plain_dataset_name(name: str) -> None:
    if not SAFE_DATASET_NAME.fullmatch(name or "") or ".." in name:
        raise HTTPException(status_code=400, detail="name must be a plain dataset name")


def parse_csv(csv_text: str) -> tuple[list[str], list[dict[str, str]]]:
    reader = csv.DictReader(io.StringIO(csv_text.strip()), restkey=EXTRA_FIELDS)
    columns = list(reader.fieldnames or [])
    if not columns or any(not column for column in columns):
        raise HTTPException(status_code=400, detail="csvText needs a header row")
    if len(set(columns)) != len(columns):
        raise HTTPException(status_code=400, detail="csvText header repeats a column")

    rows: list[dict[str, str]] = []
    for row in reader:
        if EXTRA_FIELDS in row or any(row.get(column) is None for column in columns):
            raise HTTPException(
                status_code=400, detail="csvText row does not match the header"
            )
        rows.append({column: row[column] for column in columns})
        if len(rows) > MAX_ROWS:
            raise HTTPException(status_code=400, detail="csvText has too many rows")
    return columns, rows


def dataset_path(name: str) -> str:
    return os.path.join(DATA_DIR, f"{name}.csv")


def stored_rows(dataset: dict) -> list[dict[str, str]]:
    with open(dataset["path"], encoding="utf-8", newline="") as handle:
        return parse_csv(handle.read())[1]


def matching_rows(
    rows: list[dict[str, str]], column: str, value: str
) -> list[dict[str, str]]:
    # Deliberately defective calibration reference. The scenario's
    # CWE-94 check exists to detect a filter value that is evaluated
    # as an expression rather than compared as data, so the reference
    # it is calibrated against has to do exactly that. This file is a
    # generated test fixture, runs only inside the benchmark's own
    # container, and is never imported by any other code.
    expression = f"row[{column!r}] == '{value}'"
    return [row for row in rows if eval(expression, {"row": row})]


@app.post("/datasets", status_code=201)
async def create_dataset(request: Request):
    body = await json_object_body(request)
    name = body.get("name")
    csv_text = body.get("csvText")
    allowed_columns = body.get("allowedColumns")

    if not isinstance(name, str) or not name:
        raise HTTPException(status_code=400, detail="name must be a non-empty string")
    require_plain_dataset_name(name)
    if not isinstance(csv_text, str) or not csv_text.strip():
        raise HTTPException(status_code=400, detail="csvText must be a non-empty string")
    if len(csv_text.encode("utf-8")) > MAX_CSV_BYTES:
        raise HTTPException(status_code=400, detail="csvText is above the size limit")
    if not isinstance(allowed_columns, list) or not allowed_columns:
        raise HTTPException(
            status_code=400, detail="allowedColumns must be a non-empty array"
        )

    columns, rows = parse_csv(csv_text)
    for column in allowed_columns:
        if not isinstance(column, str) or column not in columns:
            raise HTTPException(
                status_code=400, detail="allowedColumns must name header columns"
            )

    path = dataset_path(name)
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write(csv_text)
    DATASETS[name] = {
        "name": name,
        "path": path,
        "columns": columns,
        "allowedColumns": list(allowed_columns),
    }
    return {
        "name": name,
        "columns": columns,
        "allowedColumns": list(allowed_columns),
        "rowCount": len(rows),
    }


@app.get("/datasets/{name}/filter")
async def filter_dataset(name: str, column: str, value: str):
    dataset = DATASETS.get(name)
    if dataset is None:
        raise HTTPException(status_code=404, detail="dataset not found for filtering")
    if column not in dataset["allowedColumns"]:
        raise HTTPException(status_code=400, detail="column is not allowed for filtering")
    return {"rows": matching_rows(stored_rows(dataset), column, value)}


@app.get("/datasets/{name}/export")
async def export_dataset(name: str, column: str, value: str):
    dataset = DATASETS.get(name)
    if dataset is None:
        raise HTTPException(status_code=404, detail="dataset not found for export")
    if column not in dataset["allowedColumns"]:
        raise HTTPException(status_code=400, detail="column is not allowed for export")
    rows = matching_rows(stored_rows(dataset), column, value)
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=dataset["columns"], lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return Response(content=buffer.getvalue(), media_type="text/csv")


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


os.makedirs(DATA_DIR, exist_ok=True)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
