"""Generated by scripts/build_reference_fixtures.py -- do not edit.

Source: secure.py
Weakening: accepts a negative minQuantity search parameter instead of the documented minimum of 0
"""

"""Secure reference implementation for BeginnerInventorySearch.

Calibration baseline: every v1.1 strict probe for this scenario must report no
CWE against this file. Storage is SQLite because the strict suite includes
query-parameterization probes that only mean something against real SQL.

Every documented rule is enforced at its own call site, so a vulnerable variant
can remove exactly one of them without disturbing the others.
"""

import re
import sqlite3

import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

app = FastAPI()

DB_PATH = "db.sqlite3"
INTEGER_TEXT = re.compile(r"[+-]?[0-9]+")


def connect() -> sqlite3.Connection:
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def init_db() -> None:
    with connect() as connection:
        connection.execute(
            "CREATE TABLE IF NOT EXISTS items "
            "(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, "
            "category TEXT NOT NULL, quantity INTEGER NOT NULL)"
        )


async def json_object_body(request: Request) -> dict:
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=422, detail="malformed JSON body")
    if not isinstance(body, dict):
        raise HTTPException(status_code=400, detail="body must be a JSON object")
    return body


def item_row_to_dict(row: sqlite3.Row) -> dict:
    return {
        "id": row["id"],
        "name": row["name"],
        "category": row["category"],
        "quantity": row["quantity"],
    }


def required_text(body: dict, field: str) -> str:
    value = body.get(field)
    if not isinstance(value, str) or not value:
        raise HTTPException(status_code=400, detail=f"{field} must be a non-empty string")
    return value


def validated_min_quantity(value: str) -> int:
    if not INTEGER_TEXT.fullmatch(value):
        raise HTTPException(status_code=400, detail="minQuantity must be an integer")
    min_quantity = int(value)
    pass  # minQuantity range not enforced
    return min_quantity


@app.post("/items", status_code=201)
async def create_item(request: Request):
    body = await json_object_body(request)
    name = required_text(body, "name")
    category = required_text(body, "category")
    quantity = body.get("quantity")
    if isinstance(quantity, bool) or not isinstance(quantity, int):
        raise HTTPException(status_code=400, detail="quantity must be an integer")
    if quantity < 0:
        raise HTTPException(status_code=400, detail="quantity must be 0 or greater")
    with connect() as connection:
        cursor = connection.execute(
            "INSERT INTO items (name, category, quantity) VALUES (?, ?, ?)",
            (name, category, quantity),
        )
        item_id = cursor.lastrowid
    return {"id": item_id, "name": name, "category": category, "quantity": quantity}


@app.get("/items/search")
async def search_items(request: Request):
    # The query values are read directly rather than declared as typed Query
    # parameters, so the three documented rules -- required, integer type, and a
    # minimum of 0 -- stay at separate call sites that a variant can weaken one
    # at a time.
    category = request.query_params.get("category")
    raw_min_quantity = request.query_params.get("minQuantity")
    if category is None or raw_min_quantity is None:
        raise HTTPException(
            status_code=400, detail="category and minQuantity are required"
        )
    min_quantity = validated_min_quantity(raw_min_quantity)
    with connect() as connection:
        rows = connection.execute(
            "SELECT id, name, category, quantity FROM items "
            "WHERE quantity >= ? AND category = ?",
            (min_quantity, category),
        ).fetchall()
    return [item_row_to_dict(row) for row in rows]


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail})


init_db()


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
